- README.md
- src/gridstack.js
Hi,
I noticed that there is no direct way to insert a widget from a mouse click or drag&drop of an outside DOM element, as it's needed to resolve the coordinates of the future widget in grid coordinates (row, column).
This PR add a new method get_cell_from_pixel() which will return the row and column corresponding to a pixel coordinates. The input parameter can be directly taken from a drop event from jQueryUI or a mouse event, as in both case they are available as document coordinates.
> Get grid coordinates from a pixel position

- README.md
- src/gridstack.js
Hi,
The add_widget() method does not return any value right now. It would be helpful to have the fresh widget returned in order to have a reference available and direct access to its data.
> Return new widget on add_widget() call

- src/gridstack.js
Cannot sort by the node width otherwise elements which have less width but are supposed to be further down the grid (like bottom right corner for example) end up getting packed and pushed to the top right corner.
By using node.width as a weight for Y, that weight varies per node and causes random undesirable effects.
> Improper sorting with respect to nodes of variable widths

- src/gridstack.js
$(window).width() is incorrect by about 5 pixels, causing _is_one_column_mode to be incorrect. To test this, go to any gridstack and make the page width 769px. Single column mode via CSS will not kick in, yet elements will not be draggable.
> _is_one_column_mode unreliable within five pixels

- README.md
... Sorry this was bothering me.
> Fixing grammatical error

- README.md
- src/gridstack.js
Trigger change event for add_widget / remove_widget methods and refactor
the trigger into a method for uniformity
Fix issue #167
> Trigger change event for add/remove

- README.md
I've created a gem to make integration into a rails project easy. I'll use the same version tagging as you (starting from 0.2.3) and keep a master branch up-to-date with your development version.
If you don't mind, this PR add the link to my gem in your readme.
Cheers
> Rails gem link

- src/gridstack.js
In our app we are clearing the grid and then reprinting the DOM and telling gridstack to reinitialize. When that happens, the placeholder div is still around and gets moved up to the top 0, 0 position. After reinitializing, elements get pushed down because of the placeholder (even though it is display: none).
This PR simply makes sure not to look for placeholders when calling `_prepare_element`.
> Placeholder takes up space when clearing the grid

- package.json
This allows use via `require()` as a CommonJS module in Node.js, Browserify, etc.
> Add main property to package.json to enable use via require()

- dist/gridstack.js
- src/gridstack.js
When using a a lot of columns, e.g. more than 40
then the dashed box showing the next placement would
behave strangely compared to the box I am currently
dragging. This behavior increases while dragging
the box to the right side.
When scaling a box on the right side, the box would
jump one column to the left, which would then move around
all the boxes that I have already placed.
This behavior seems to be related to a rounding problem.
> [BUGFIX] offset problems for dragging and scaling with a lot of columns

- src/gridstack.js
On touch devices, it's not possible to scroll a page by dragging on an item even when draggable is
disabled due to the **ui-draggable-handle** class which is added to the **grid-stack-item-content**
JQuery-UI Draggable doesn't remove this class when it's disabled, so it prevents touch scrolling the page on the item
```
<div class="grid-stack-item-content ui-draggable-handle">
.ui-draggable-handle {
-ms-touch-action: none;
touch-action: none;
}
```
> toggle ui-draggable-handle class with draggable

- README.md
- src/gridstack.js
For simplified reaction on enabling and disabling of gridstack containers, two events enable and disable were added to the API.
> Adding enable and disable events

- README.md
- src/gridstack.js
When using gridstack.js together with Angular, gridstack widgets can be added to the DOM by using Angular's `ng-repeat`. Gridstack should therefore offer an API method, that allows us to convert an element to a widget (without creating the DOM elements). I prefer to not add this functionality to `add_widget`, because it could lead to conflicts with the `data-gs` variables and the parameters. The `make_widget` method provides a clean way to make a widget without letting gridstack do DOM manipulations.
Related https://github.com/troolee/gridstack.js/issues/238
> Adding make_widget functionality

- dist/gridstack.js
- spec/utils-spec.js
- src/gridstack.js
It should be possible to call for example the verticalMargin method with negative numbers.
verticalMargin('-5px')
Instead of bypassing the method
grid.opts.verticalMarginUnit = 'px';
grid.opts.verticalMargin = '-5';
grid._updateStyles();
> Allow negative numbers to be passed to parseHeight function

- src/gridstack.js
Add a fire resize event when gridstack pass from desktop to mobile view (one column) and vice versa.
I changed this because when gridstack change his column, every node size is changed but no one event is fire for this.
This can cause problem for content of node that have pixel width and height, and need to be update when his parent change. Like SVG, iframe or other
> Fire resize event for gridstack node when changing view

- doc/README.md
The grid switches to one column at less than or equal to minWidth rather than just less than as the docs currently state.
> Fix minWidth description

- Gruntfile.js
- package.json
To ensure uniform contributions we run the lint command
as part of testing.
> include linting for npm test

- src/gridstack.js
After calling `this._initStyles()`, the condition `this._styles._max !== 0` will never be true. And then a smaller `maxHeight` will be able to assign to `this._styles._max`, and this will cause the missing of some style rules.
> bug fix: keep this._styles._max increasing

- src/gridstack.js
Instead of removing all inline styles on moved/cloned items via `removeAttr('style')`, it's better to remove just the positioning styles that were previously added.
> Preserve inline styles when moving/cloning items

- src/gridstack.js
Old getCellFromPixel call used ui.offset, which has the position of the upper left corner of the dragged item, but we need to track the mouse position.
> Some fixes when dropping external items.

- src/gridstack.js
`_packNodes` did not work correctly in floating mode for nodes of height > 1. When trying to move such a node upwards, the repositioned node intersected with its previous position. Fix this by only checking for collisions with preceding nodes instead of all nodes.
> Avoid collision check of node with itself. Fixes #586

- src/gridstack.jQueryUI.js
- src/gridstack.js
made the "trashzone" configurable through the "removableOptions". All the jq ui options should be supported now
added an "inTrashZone" flag to fix a problem when there is an overlapping between the grid and the "trashzone"
PS I'm not very experienced in github / jq plugins, hope I didn't break anything... if accepted the information about "removableOptions" parameter should be added to the readme doc
> "trashzone" improvement

- doc/CHANGES.md
- src/gridstack.js
Piggyback on idea from https://github.com/gridstack/gridstack.js/pull/648 - when x and y coordinates for widgets are stored, run `parseInt(num, 10)` to ensure that they're treated as integers when sorting.
> Update documentation and force x/y coords to be stores as ints.

- karma.conf.js
- package-lock.json
- package.json
Addresses #781. The karma test script previously relied upon jquery-ui, jquery, and lodash being in `bower_components`. Since each is declared as a dependencies, it makes more sense to import them from `node_modules`. I added a dev dependency for jquery-ui because the official `jquery-ui` package does not provide a bundle of the internal scripts.
> make tests rely upon dependencies in node_modules

- spec/gridstack-spec.js
- src/gridstack.js
the code that checked for cell height and unit being the same was incorrect.
Testing Done:  calling this should be no-op, but wasn't
this.grid.cellHeight( this.grid.cellHeight() );
code right below uses correct names
this.opts.cellHeightUnit = heightData.unit;
this.opts.cellHeight = heightData.height;
P.S. this is why Typescript is good - you don't do those stupid JS typos....
> fixed cellHeight() check for no-op return

- src/gridstack.js
When there are 4 row of grid items and more. There are bug of updates styles. 
The function does not take into account all nodes, but only those that have been changed (_dirty).
In this regard, the styles for the lower layers do not sink, and they rise upward.
The solution is to calculate the maxHeight for all nodes.
Bug example - https://youtu.be/1bZQIaZqVLQ
> Bug wrong maxHeight for updateStyles function

- doc/README.md
The link to the demo of the `acceptWidgets` option which was outdated.
> Fix link to acceptWidgets example

- doc/README.md
Url's in the API doc where referring to non existing pages. Changed them to the right ones.
> Change urls in API doc

- src/gridstack.js
Frequent Transient Bug when moving or resizing
issue-805 - fix node being added to grid more than once after being dragged out of bounds
Description of issue
After a grid item was dragged out of bounds there were extra node being added to the grid.  This caused the node to get stuck. 
See video:  https://youtu.be/QJj6hi7lnDU.
Solution:
Node only gets re-added once, after being dragged out of bounds.  Set "node._temporaryRemoved" to false when adding node back into grid the first time.  This prevents multiple calls to addNode().
> issue-805 - fix node being added to grid more than once after being dragged out of bounds

- README.md
I updated the SASS code snippet in README.md to more directly reference the gridstack item, and avoid problems where the widths of the gridstack items, are still set by gridstack.css and not this code. See issue [#868](https://github.com/gridstack/gridstack.js/issues/868) for an example.
> Updated SASS code snippet in README.md

- README.md
- bower.json
- demo/anijs.html
- demo/float.html
- demo/knockout.html
- demo/knockout2.html
- demo/nested.html
- demo/responsive.html
- demo/rtl.html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- package-lock.json
- package.json
- src/gridstack.js
Fix #882 by preventing widget from checking if it can move when it has been excised from the grid.
> Fix #882, set version at 1.0.0-dev, update demos to use lodash 4.

- doc/README.md
On `batchUpdate()` documentation, `Initializes` was incorrectly typed as `Initailizes`.
Just fixed a typo on `batchUpdate()` documentation.
> Fixed typo

- src/gridstack.js
Requiring `jQuery` and `_` without a `var` declaration were overwriting the global implementations of those libraries if they exist.
Because `jQuery` and `_` can be customized and configured, it would be best to keep internal dependencies isolated.
I have a 2018 MBP and `npm test` does not run for me -- Karma simply times out. Since this falls back to the global versions, I don't foresee any tests failing. But please let me know if I'm missing a step to get tests running locally.
> Don't overwrite globals when in a modular environment.

- src/gridstack.scss
* there is no need for the regular grid content to have a topmost z-index
(dragging and placeholder still render on top unchanged)
this was causing modal dialogs to grid content to be clipped and not render correctly
I test two.html and another testc ase and see no differences in z-ordering.
instead of the correct modal (OK button from grid item).
> removed item-content z-index

- doc/README.md
documentation fix for https://github.com/gridstack/gridstack.js/pull/978 which should be closed (incorrect)
> fixed gsresizestop doc

- README.md
- bower.json
- doc/CHANGES.md
- package.json
- src/gridstack.jQueryUI.js
- src/gridstack.js
> prep for 0.5.0 release

- demo/anijs.html
- demo/float.html
- demo/knockout.html
- demo/knockout2.html
- demo/nested.html
- demo/responsive.html
- demo/rtl.html
- demo/serialization.html
- demo/two.html
- spec/e2e/html/gridstack-with-height.html
- src/gridstack.js
- yarn.lock
* did a 'yarn upgrade' to get latest compatible lib for .lock file
* updated all samples to latest version on CDN. Tested each one on Chrome
test each sample app before/after change (Chrome)
> upgraded to latest rev of libs

- README.md
- doc/CHANGES.md
removed 1.0 release doc info as it was causing generated doc to be modified on each builds (git mod).
We can add it back if/when it makes sense.
> removed 1.0 release doc info

- index.html
fix url to gridster.js using https://github.com/ducksboard/gridster.js instead of gridster.net which is malware now - see #917
manual editing, no easy way to test change,
> fix url to gridster.js

- README.md
- doc/README.md
- karma.conf.js
- spec/e2e/gridstack-html-spec.js
- spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
- spec/e2e/html/gridstack-with-height.html
- spec/utils-spec.js
- src/gridstack.js
fix for #1017 (missing x,y breaks grid), but also a long time issue with
autoPlacement=true not respecting DOM order to place items (missing x,y or zero values)
(bugged me for a while, so glad to tackle it)
* no longer force x,y to be integer up front (get Nan when missing),
instead we detect missing and set autoPosition=true. They get fixed soon after.
* fixed Utils.defaults() field assignment to check for x=undefined not just missing
* fixed code that sorted elements to be created to put autoPosition items last
while keeping DOM order.
* added karma test cases and UI HTML sample showing complex case - to make
sure it doesn't break going forward.
* fixed README & others CDN locations to use https:// so we can test them locally.
TODO: karma test on HTML file wasn't working, so mine isn't …
> undefined x,y position messed up grid

- README.md
- bower.json
- doc/CHANGES.md
- package.json
- src/gridstack.jQueryUI.js
- src/gridstack.js
* for CDN switched to cdn.jsdelivr.net which has the latest 0.5.1 images (cdnjs.cloudflare.com does not)
> v0.5.1-dev label, CDN url fix

- package.json
- yarn.lock
locked the following 2 indirect dependencies to remove critical/sever security risk, as per github
"lodash": "^4.17.13",
"js-yaml": "^3.13.1"
> lock package dependency for security warning

- demo/two.html
- doc/CHANGES.md
- src/gridstack.js
*method was not correctly counting margin when figuring out minHeight during a drag
(see gridstack#999)
* fixed cellHeight() getter to correctly returns the value and checked all places that use to adjust for margins
I tested two.html as well as my app that doesn't a lot of drag&drop and made sure things resized correctly and no new issue, but min size is now correct (see #999 screen shots)
> onStartMoving() fix to minHeight (#999)

- demo/float.html
- demo/responsive.html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/gridstack-with-height.html
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
fix for #907 
* new addWidget(el, options) to pass object so you don't have to spell 10 params
* updated TS file, test case, some samples
* also renamed IGridstackOptions to GridstackOptions (angular/TS style guide avoid cap I for interfaces, the others were correct already).
> addWidget(el, options) with object param

- demo/anijs.html
- demo/float.html
- demo/serialization.html
- src/gridstack.js
* changed all == to ===, != to !== (no unwanted side affect)
* changed (typeof foo !== 'undefined') to (foo !== undefined)
* shorten the test cases for all but first 2 instances than check for global vars
* in some browser this can be a lot faster too (80% on Edge)
https://jsperf.com/type-of-undefined-vs-undefined/30
* shorter notation. in some case just if (foo) as we should check for null as well
(if there are not 0 number cases)
* fix demos to have regular buttons - latest bootstrap make them flat (no border)
ran all tests and demos. no issues.
> code cleanup

- README.md
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/810-many-columns.css
- spec/e2e/html/810-many-columns.html
- spec/gridstack-engine-spec.js
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
* grid options `width` is now `columns`, and `height` is now `maxRows` which match what they are.
* Old names are still supported for now (with console warnings)
* updated test (required), samples (optional), readme
* re-wrote entire custom column section. Hopefully much easier to find/use now.
Created a sample for #810 with 30 columns, but not seeing issues in that PR (issue rounding cellWidth() with large # of columns). I was able to move and resize and things lined up as expected even when total width / 30 was close to .5 off 
@nulen please update with info.
In the meantime I found those issues:
* fix README talking about custom columns #
* fix SASS code to handle >12 columns as you need to override stack-item min-width (we have 8.3333% otherwise which is 12 column!)
* while testing I …
> grid options renamed to `columns` & `maxRows`

- README.md
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/810-many-columns.html
- spec/gridstack-engine-spec.js
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
tweaks to #1053 that should use singular instead of plurals.
> change grid prop to 'column' & 'maxRow' (singular)

- demo/column.html
- demo/responsive.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
part of #1053 changes
* kept old method as stub with warning (no code break)
* added new (hidden for now) column.html demo
* updated test coverage
> renamed setGridWidth() to setColumn()

- Gruntfile.js
- README.md
- demo/anijs.html
- demo/float.html
- demo/knockout.html
- demo/knockout2.html
- demo/nested.html
- demo/responsive.html
- demo/right-to-left(rtl).html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- package.json
- spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
- spec/e2e/html/810-many-columns.html
- spec/e2e/html/column.html
- spec/e2e/html/gridstack-with-height.html
- src/gridstack.jQueryUI.js
- src/gridstack.js
- src/gridstack.poly.js
* tiny file now part of all.js output.
* removed core-js from samples (>85k zipped) as we only needed 2 methods anyway
* removed all IE8 mentions, updated docs.
* tested on IE11, Chrome, Firefox, Edge
> new `gridstack.poly.js` for IE and older browsers

- README.md
- doc/CHANGES.md
- package.json
- yarn.lock
fixes #629
* tested samples and lowest we can use is 1.8 (1.7 gives us .addBack() missing for jqUI 1.12)
* I don't see any harm is listing a wider range. Still using latest locally (smaller)
> changed jquery to "^1.8 || 2 || 3"

- doc/CHANGES.md
- spec/gridstack-spec.js
- src/gridstack.js
fix for #1054
* had incorrect check for 0 value (valid) when sorting objects. Checking NaN instead.
* this was introduced when fixing #1017
> griditems with x=0 placement fix

- doc/CHANGES.md
- spec/gridstack-spec.js
- src/gridstack.js
as it is causing cellheight() to fail (#1068) which is worse and more common than missing animation.
> reverted #1047 (updating styles)

- demo/anijs.html
- demo/demo.css
- demo/float.html
- demo/knockout.html
- demo/knockout2.html
- demo/nested.html
- demo/responsive.html
- demo/right-to-left(rtl).html
- demo/serialization.html
- demo/two.html
- spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
- spec/e2e/html/810-many-columns.html
- spec/e2e/html/column.html
- spec/e2e/html/gridstack-with-height.html
* bootstrap .css and .js removed, other than two.html which uses column class
* added simple demo.css for shared button/grid styles (one place)
simplifies the includes a lot, focus on gridstack code
ran each demos
> removed bootstrap from demos

- .gitignore
- .npmignore
- doc/CHANGES.md
- src/gridstack.d.ts
need to verify before pushing new NPM images... had extra stuff in 0.5.4 (since it includes everything but listed skip items).
> npm package fix to exclude more temporary content

- doc/README.md
Corrected the alphabetical order of options in doc.
> corrected the alphabetical order of options in doc

- demo/float.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-engine-spec.js
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
* add `float(val?)` set/get method to change the grid option, which will relayout widgets when gravity is back on
* renamed internal `_updateCounter` (number)  to `_batchMode` (boolean) was never a counter to begin with.
* float.html and two.html now has buttons to toggles mode
> add float(val?) set/get method

- doc/CHANGES.md
- doc/README.md
- spec/utils-spec.js
- src/gridstack.d.ts
- src/gridstack.js
from #748 which I couldn't merge, plus doc and test case update.
> Allow percentage as a valid unit for height

- README.md
- demo/advance.html
- demo/responsive.html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/column.html
- spec/e2e/html/gridstack-with-height.html
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
* fixed callbacks to get either `added, removed, change` or combination if adding a node require also to change its (x,y) for example
(we use to always get 'change' duplicated callback)
* you can now call `batchUpdate()` before calling a bunch of `addWidget()` and get a single event callback (more efficient).
* update two.hml to show callbacks (good debuging setup)
Note: moving items in float=false will still sometimes have change CB with all items, not just those that moved. this is due to how _fixCollisions() does this
`
if (!this.float && !hasLocked) {
nn = {x: 0, y: node.y, width: this.column, height: node.height};
}`
causing all items to temporarly move. I don't claim to understand that code yet...
* added a comment for #789 as to why _packNodes() can't check for
`n._dirty = n._origY …
> fixed callbacks types

- demo/responsive.html
- demo/serialization.html
- doc/CHANGES.md
- spec/e2e/html/gridstack-with-height.html
- spec/gridstack-spec.js
- src/gridstack.js
* `removeAll()` is now much faster as it doesn't cause any relayout (added GridStackEngine.removeAll to optimize)
* it now calls `removed` event back just once with a list of nodes
* _removedNodes uses actual nodes (not clones)
better fix than #551, related to previous #1096
> much faster removeAll(), single event trigger

- demo/column.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
new compact() method
* relayout grid items to reclaim any empty space
* update two.html demo to have a compact button, and test case
also (separate PR)
tweaks to setColumn()
* improved code, now using gridEngine.addNode() instead of removeAll() + addWidget() which is much lighter now
* use a higher res layout when going up and cache is missing
(better to down-sample say from 12 then up-sample from 1!)
#1098 part 2
> new compact() method, improved setColumn()

- demo/column.html
- demo/float.html
- spec/gridstack-spec.js
- src/gridstack.js
* restored `_updateNodeWidths()` which setColumn() calls (split code into GridStackEngine)
* added `_layoutsNodesChange(nodes)` - called whenever a node is added or moved to update the cached layouts
(clears lower one, update higher ones)
> more setColumn() tweaks

- demo/nested.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.jQueryUI.js
fix for #720 #386 #695
* new `options.dragOut` to let user drag nested grid items out of a parent or not (default false)
* Jquery UI `draggable.containment` can now be specified in options as well
* updated nested.html demo app to show ability to drag&drop between 2 nested grids
and constrain or not to parent.
thank you @trevisanweb @aureality @ZoolWay for supplying the code & info!
> drag&drop between nested grids, set Containment

- demo/float.html
- demo/nested.html
- src/gridstack.d.ts
* #95 works in the current node
* nested.html now has add widget buttons.
> demo showing adding item to nested grid

- demo/two.html
- doc/CHANGES.md
- src/gridstack.js
* you can now pre-define size of dragable elements from a sidebar using standard `data-gs-width` and `data-gs-height`
* updated two.html to show that
* also faster node sorting (removed multiply)
fix for #413 #914 #918 #922 (and others) and especially #933 which had the issue spelled out by @ermcgrat.
Sorry it took so longer to add this!
> define size of dragable elements from a sidebar

- demo/two.html
- doc/README.md
- src/gridstack.d.ts
* fixed doc and updated two.html with actual example
* fix for #1113
> acceptWidgets better doc

- doc/CHANGES.md
- src/gridstack.d.ts
- src/gridstack.js
- src/gridstack.scss
* one column mode (<768px by default) now simply calls `setColumn(1)` and remembers prev columns (so we can restore).
* This gives us full resize/re-order of items capabilities rather than a locked CSS only layout (see prev rev changes).
* continuation of #1098, will affect #966 as well
* NEXT: fix responsive.html which has been broken for a while.
> OneColumnMode use setColumn(1)

- demo/column.html
- demo/responsive.html
- doc/CHANGES.md
fix reponsive.html demo
part of #1120 #1098
> fix reponsive.html demo

- doc/CHANGES.md
- src/gridstack.js
* window resize only need to restor back to non oneColumn if we auto went into 1 column (as opposed to user calling setColumn(1) in a large window)
* this was causing column.html editing in 1 column to jump back to 12.
* introduced by my last change #1120
> oneColumnMode bug fix

- demo/column.html
- doc/CHANGES.md
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
* add `oneColumnModeDomSort` true|false to let you specify a custom layout (use dom order instead of x,y) for oneColumnMode `setColumn(1)`
* fix for #713
* better than PR #966 which attempted to make a generic support for oneColumn only mode, yet didn't modify the other layouts sorting.
Instead user will have complete control (dom order) iresptive of layouts sort.
Also works with current setColumn() implementation
* added karma tests
* Note: you cannot change this flag and expect 1 column (which is cached) to change (can see in column.html,
unless you add/remove items in larger layouts the blows caches). Future todo.
> Custom Responsive Sort Order

- demo/column.html
- doc/CHANGES.md
- spec/gridstack-spec.js
- src/gridstack.js
* more fix #37 and part2 of #1120
* editing in 1 column (or few columns) does a better job updating higher layout
* track before and after and move items accordingly. Tracking item swap would be even better still
* column.html demo has been updated to support item delete.
* karma test updated
> 1 column edit propagation fixes

- README.md
- demo/column.html
- demo/index.html
- doc/CHANGES.md
- src/gridstack-extra.scss
- src/gridstack.scss
* fix for #1132 where some demos had incorrect 1 column layout.
* the CSS for `.grid-stack-1` is now part of default css (was in extra.css)
* also tweaked SASS to only generate 2-11 columns for extra.css and documentation changes.
> fixed oneColumnMode css

- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.js
- src/gridstack.d.ts
- src/gridstack.js
* If you depended on this, use class `.grid-stack-1` instead of `.grid-stack-one-column-mode` since it is 1 column layout anyway
* updated jasmin test
* should have been done in #1120
> removed `oneColumnModeClass` and associated code

- demo/anijs.html
- demo/column.html
- demo/float.html
- demo/index.html
- demo/knockout.html
- demo/knockout2.html
- demo/nested.html
- demo/responsive.html
- demo/right-to-left(rtl).html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/810-many-columns.html
- spec/e2e/html/gridstack-with-height.html
- spec/gridstack-spec.js
- spec/gridstack-tests.ts
- src/gridstack.d.ts
- src/gridstack.js
***BREAKING CHANGE***
* `gridstack()` init method will no longer return a JQuery object
(part of removing JQ from our API),
but rather `GridStack | GridStack[]` (if multiple are present) making it much more convenient.
* Instead of:
`
$('.grid-stack').gridstack(opt);
var grid = $('.grid-stack').data('gridstack');
`
you can now just:
`
var grid = $('.grid-stack').gridstack(opt);
`
> `gridstack()` init method return GridStack ** BREAKING CHANGE***

- doc/CHANGES.md
- spec/e2e/html/1142_change_event_missing.html
- src/gridstack.js
* fix for #1142
* make sure to call any other change when adding/removing widgets
* this right now can call extra uncessary change CB at times, but better than not calling on nodes that changed.
> RemoveWidget() now call _triggerChangeEvent()

- demo/column.html
- demo/two.html
- doc/CHANGES.md
- src/gridstack.js
* save original x,y,w,h values and only call those that changed
(and not just tempory flag _dirty)
* getting all the test cases was tricky. Used all demos with some mods.
* related to #1147 which fixes #1142
> optimized `change` callback

- doc/CHANGES.md
- spec/e2e/html/1143_nested_acceptWidget_types.html
- src/gridstack.js
* fix for #1143
* added sample test where parent and nested grid have different drop class support
* while `this.dd.droppable.accept()` does check for
`el.is(self.opts.acceptWidgets === true ? '.grid-stack-item' : self.opts.acceptWidgets)`
to prevent wrong items from being dropped, the problem was that `dropover|dropout|drop` handlers did NOT return false so the parent grid was getting them as well, causing error
> fix nested grids with different `acceptWidgets` class

- README.md
- doc/CHANGES.md
- src/gridstack.js
* insert style before our grid (instead of head) to support webcomponent
* fix #540
* tested on Chrome, FF, Edge, IE11 and all our demos
*Note: I didn't have a way to test webcomponent support, but this should do it.
> WebComponent support

- src/gridstack.js
> fix resize not taking margin height

- doc/CHANGES.md
- src/gridstack.js
* better fix for #1166, the next resize up is now exactly mid point
> fix Resizing does not work as expected

- doc/CHANGES.md
- spec/gridstack-spec.js
- src/gridstack.js
* it was possible before to `addWidget()` outside of a maxRow limit, causing the item to not be draggable
* had to be careful not to break knockout demos
* fix for #1155
> `maxRow` now limit initial item placement

- demo/advance.html
- demo/column.html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1142_change_event_missing.html
- spec/e2e/html/1143_nested_acceptWidget_types.html
- spec/e2e/html/events.html
- src/gridstack.d.ts
- src/gridstack.js
* added event support to call `grid.on('added removed change', callback)`
again even with native events (was jquery feature)
* updated demos to use it (like it!)
* fix for #1171
- [X Extended the README / documentation, if necessary
> added multiple event callbacks

- doc/README.md
- src/gridstack.js
Added `minRow` and `row` properties.
- `minRow`: Minimum amount of rows to generate, default is 0.
- `row`: Shortcut to have same value for `minRow` and `maxRow`.
> Added minRow and row

- src/gridstack-poly.js
> Add polyfill for CustomEvent to fix #1186

- README.md
> better doc for jquery conflict

- Gruntfile.js
- README.md
- doc/CHANGES.md
- src/gridstack-extra.scss
* including the source SASS files for the package (like before)
as some app/lib might use it to generate extra column layouts
* updated README with sample code
* see https://github.com/node-red/node-red-dashboard/issues/569
> include SASS src files to npm pack

- Gruntfile.js
- src/gridstack-extra.scss
- src/utils.ts
complement @btecu upcoming changes (now have TS code compile and load)
> TS: fix obsoleteAttr() issue

- demo/float.html
- demo/two.html
- src/gridstack-dragdrop-plugin.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/jqueryui-gridstack-dragdrop-plugin.ts
- src/types.ts
* removed most JQ code in gridstack.ts, some harder parts remain.
* changed `.${val}` to just '.'+val to make it easier to search for $ replacement
* continued #1084
Note: float.html finally loads for me and add widget works! BUT drag/drop is still broken...
> TS: more jquery removal

- .eslintrc.js
- package.json
> TS: Fix lint command on Windows

- demo/float.html
- doc/CHANGES.md
- src/gridstack.jQueryUI.js
- src/gridstack.js
* calling `grid.destroy(false)` will clean things and let you init() again.
* removing an item will now nuke  jquery drag&drop using `draggable('destroy')` instead of just disabling.
This also removes all JQ styles added if you keep DOM element around.
* also removes extra grid style left behind
* fix for #1204
> destroy drag&drop when removing node(s)

- .eslintrc.js
- README.md
- demo/advance.html
- demo/anijs.html
- demo/column.html
- demo/float.html
- demo/knockout.html
- demo/nested.html
- demo/responsive.html
- demo/right-to-left(rtl).html
- demo/serialization.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.js
- src/gridstack-dragdrop-plugin.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/jqueryui-gridstack-dragdrop-plugin.ts
- src/types.ts
- src/utils.ts
- tsconfig.json
- yarn.lock
* removed a bunch more jquery code in main file
(more drag&drop will need to move out)
* all the demos are finally running, found a bunch of issues of DOM vs jquery
->all but knockout which always inserts at (0,0) now
-> RTL works a little better now, but still broken (hasn't worked in a while)
* public API that take string | HTMLElement will now handle list with selector
* using 'let' everywhere since not real global const
* matches latest develop code fixes
more #1084
TODO: fix lint and test cases next...
> TS: working demos

- .eslintrc.js
- .vscode/settings.json
- karma.conf.js
- package.json
- spec/gridstack-engine-spec.js
- src/gridstack-dragdrop-plugin.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/jqueryui-gridstack-dragdrop-plugin.ts
- src/types.ts
- src/utils.ts
- yarn.lock
* we now pass `yarn lint` stage
* removed more jquery calls
* `yarn test` is stuck with a 2min timeout
```cmd
HeadlessChrome 80.0.3987 (Windows 10.0.0): Executed 0 of 106 SUCCESS (0 secs / 0 secs)
HeadlessChrome 80.0.3987 (Windows 10.0.0) ERROR
Disconnectedreconnect failed before timeout of 2000ms (ping timeout)
HeadlessChrome 80.0.3987 (Windows 10.0.0): Executed 0 of 106 DISCONNECTED (32.002 secs / 0 secs)
```
* part of #1084
> TS: lint fix and more jq removal

- src/gridstack.ts
Small change to remove more jQuery dependencies, although I haven't tested it.
> No more `$(el).children()`

- doc/CHANGES.md
- src/gridstack.ts
continue @btecu work to extract `$(el).children()` out
> TS: added `getGridItems()`

- src/gridstack.js
I made the `Gridstack.initAll()` function use a deep copy of the `opts` object by using `JSON.parse(JSON.stringify(opts))`(Simplest method I found, that fixes our issue).
> Fix for issue #1217

- demo/experiment/locked.html
- doc/CHANGES.md
- spec/gridstack-engine-spec.js
- src/gridstack.js
* make sure `_fixCollisions()` take node locked state into account
* `moveNode()` also checks for locked state, but resize can still happen
(forced for column layout change)
* added demo and test case showing issue
* fix #1181
> fix for locked widgets still moving by others

- README.md
- doc/README.md
- karma.conf.js
- package.json
- spec/gridstack-engine-spec.js
- spec/gridstack-spec.js
- spec/utils-spec.js
- src/gridstack.ts
- src/utils.ts
* the karma test cases are now all working again
(found some actual issues in new TS code)
* most test changes are `let` vs `var`
getSttribute() returning NULL instead of undefined
and removing jquery calls
* code coverage NOT working right now
(need to figure how to test .ts files ?)
* reverted karma.config.js for now (pre TS changes)
more #1084
> TS: karma test cases

- spec/gridstack-spec.js
- src/gridstack-engine.ts
- src/gridstack.ts
* all methods now return at least `this` so they can be chainable if they don't return something specific
* `staticGrid` no longer disable oneColumnMode
> TS: return signature cleanup, bug fix

- README.md
- demo/locked.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.js
- yarn.lock
> TS: develop -> typescript

- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack.ts
> prevent removing another grid's item

- doc/CHANGES.md
- src/gridstack.js
> clone grid option

- README.md
- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack.ts
> TS: fix 'addWidget' ignores data attributes #1276, 1.1.2 release

- demo/serialization.html
updated serialize demo to use Update() instead of clearing the nodes each time.
> #1286 updated serialize demo to use Update()

- doc/CHANGES.md
- spec/e2e/html/810-many-columns.html
- src/gridstack.ts
* cellWidth() no longer round things off
(I was able to see issue with 60 columns and dragging itelf on right and would not relocate unless moved a lot further).
> TS: fix for #810 many columns roundoff error

- README.md
- demo/nested.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
- spec/e2e/html/810-many-columns.css
- spec/e2e/html/810-many-columns.html
- spec/gridstack-spec.ts
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* complete re-write how we size/position items dealing with margin
* we now have a single `margin` grid option which will set all 4 sides instead of one in code nad one in CSS
* also have `marginTop/Bottom/Left/Right` if more precise setting is required
* greatly reduced the layout code as margin are now inside the grid-item
(affects content)
* fixed code so `cellHeight: 'auto'` (now the default) will create real square cells
(used to be off due to margin)
* grid will now have consistent spacing (above/below first/last rows)
> TS: #723 #726 `margin` to replace `verticalMargin`

- README.md
- demo/experiment/test.html
- doc/CHANGES.md
- src/jq/jquery.js
> TS: jquery v3.5.1

- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.js
- src/gridstack.js
This change allows for keeping older behavior of gridstack where `<STYLE>` was added to `<HEAD>` instead of parentNode. The default behavior remains to be to use parentNode but in situations where `head` is preferrable just pass `styleInHead = true` to gridstack options.
> adding styleInHead option

- README.md
- doc/CHANGES.md
- src/jquery.js
> update jquery to v3.5.1

- demo/serialization.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- src/gridstack.ts
* more fix for #1286
* changed method to load() (rather than restore())
* added a callback function in additon to boolean which default to true (will add/remove widgets by default)
> TS: support callback for load()

- README.md
- demo/advance.html
- demo/events.js
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1102-button-between-grids.html
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
re-write of D&D with generic non jquery code. this fixes the following:
* #1329 D&D wasn't working correctly in 2.0.0-rc
went through entire code with fine comb. "had to change 'drop' signature to have 2 elements (original drag and helper) do handle both cases
* #1102 we no longer make a copy when dragging between grids (just re-parent)
so all actions and settings stay the same.
Only time we make a copy is if dragging from an external toolbar and user has helper to clone item
> TS: drag&drop fixes

- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
> removeWidget() doc update

- src/gridstack.ts
* make sure we remove drag&drop handler
* reset el.gridstackNode before callback to let callee know it's going away.
* Only remove if not already done.
> TS: tweaks to 'removed' callback

- README.md
- src/gridstack.jQueryUI.js
- src/gridstack.js
- src/jquery-ui.js
Since v1.0.0 the UMD code at the top of the files has been disabled, preventing someone using a bundler to provide jQuery via the module system. Therefore if one's not including the gridstack.all.js directly in HTML, it is mandatory to have jQuery accessible globally via the `window` object.
I propose to enable back the UMD code in order to be able to use a bundler like webpack with gridstack v1
I have also modified the Readme file in order to reflect this change : gridstack.all.js should not be used with a bundler, instead we just need the gridstack lib files. A reference to the Gridstack object is retrieved via the import of gristack.js.
Will probably fix #1243 (I couldn't test this with a vue.js stack)
> Enable the UMD behavior for bundlers compatibility

- README.md
- doc/CHANGES.md
- package.json
- webpack.config.js
> TS: 2.0.0-rc3 release

- README.md
- doc/CHANGES.md
- package.json
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
- src/utils.ts
* fixed minWidth(), minHeight, maxHeight to set node value as well - see #1359
* correct GridStackOptions casing - see #1359
* rev 2.0.0-dev
> GridStackOptions casing, minWidth() fix

- spec/gridstack-spec.ts
- src/gridstack.ts
* getGridElement() no longer appends '.' or '#' as user should pass a correct selector anyway
- [X All tests passing (`yarn test`)
> fixed init() to give better error msg

- demo/vuejs.html
Added a basic example of how to integrate GridStack with a Vue.js app. This demo requires a modestly modern browser, but Vue has a legacy build mode when using single file components with Vue CLI. I added a few lines about common pitfalls when integrating a DOM-dependent library like gridstack.js with virtualDOM frameworks.
> Add Vue.js example

- README.md
Documentation change only.
Updates the section about using `gridstack-extra.css`, so it points to the `2.0.0` version, to make it consistent with the rest of the README.
> Update gridstack-extra.css section in README to point to 2.0.0

- README.md
- demo/index.html
- demo/vuejs.html
* added to index page and readme links, tweak to code.
> vue.js example tweaks

- doc/README.md
- spec/gridstack-spec.ts
- src/gridstack.ts
* tweaks code made in #1365
* reverted back to supporting  multiple selectors, but now checking for '.' and '#' before adding them
* getGridElement() now re-uses getElement()
- [] Extended the README / documentation, if necessary
> fix to getElements() methods

- doc/CHANGES.md
- src/gridstack.ts
fix #1369, we now remove resize event correctly in destroy()
> correctly remove window resize event

- demo/nested.html
- doc/CHANGES.md
- src/gridstack.ts
* fox for #1361, we can now resize nested grids again
> fix to nested grid resisze

- demo/nested.html
- src/gridstack.ts
better fix for #1369
* `private _onResizeHandler()` is now `onParentResize()` as client might want to manually call this
(when dome div above resizes)
* we now store the event binding method to we can not just remove the handler
BUT also delete it to free class pointer
(else GridStack classs will likely not free up)
* also only top grid now register size event, children get it through parent (which happens during cell resize as well)
* only register window resize if we need to as well
> better window resize handler fix

- demo/float.html
- doc/CHANGES.md
- src/gridstack.ts
* fix for #1356
* `getCellHeight(forcePixel = false)` now take optional arg to get pixel values,
which is needed during resize calculations
* texting with example with "6em" "6rem" "auto" "70" and "70px"
> fix for resize with cellHeight in rem/em

- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* fix for #1367
* we now copy all nodes attributes when moving between grids
> preserve attributes dragging between grids

- doc/CHANGES.md
- src/gridstack.ts
* fix for #393 having 2 shadows when dragging long items between 2 grids
* when dragging an item into a grid, we now mark that it was added
for the old grid to detect and temporary remove the item.
always wanted to fix that...
> fix two drop shadows

- demo/h5dragdrop.html
- doc/CHANGES.md
- package.json
- src/dragdrop/dd-base-impl.ts
- src/dragdrop/dd-draggable.ts
- src/dragdrop/dd-droppable.ts
- src/dragdrop/dd-element.ts
- src/dragdrop/dd-manager.ts
- src/dragdrop/dd-resizable-handle.ts
- src/dragdrop/dd-resizable.ts
- src/dragdrop/dd-utils.ts
- src/dragdrop/gridstack-dd-native.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/index-html5.ts
- src/index-jq.ts
- src/index-static.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
- src/utils.ts
- webpack.config.js
* we now have 3 webpack build targets depending on which tech you want
`gridstack.all.js` - remains unchanged for now (jq ui drag&drop)
`gridstack.html5.js` - new prototype HTML5 drag&drop (125k min smaller, no jquery at all)
`gridstack.static.js` - smallest bundle for static grids (no drag&drop)
* D&D plugins is no longer a list - last one wins
* added credits, 2.0.1-dev rev number
Note: main TS code no longer includes jquery based D&D, you have to
import explicitly which drag&drop (we now have 2) you want in your ES6/TS include.
webpack bundles include all parts as mentioned above.
Note:
> HTML5 grid build support

- demo/float.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
* fix for #937, thank you @marttop for proposing a fix
* ended up re-writting the CSS creation routine and make it easier to maintain going forward.
* we now only re-create stylesheet when margin or cellHeight (the only static items) change.
Else we happen row based rules as the grids needs them (and only what it needs, not always +10)
> fix to animate

- README.md
- doc/CHANGES.md
- src/gridstack-poly.js
- src/index-html5.ts
- src/index-jq.ts
- src/index-static.ts
- tsconfig.json
#1389
* changing webpack to target ES5 (instead of ES6)
(186k -> 192k)
* adding couple polyfills helps go further along
BUT still complains
> SCRIPT438: Object doesn't support property or method 'forEach'
target.querySelectorAll('.grid-stack').forEach()
even tough I added Array.forEach (because it's a NodeListOf<E> ?)
**Note**: I am gonna punt on this mark IE11 no longer supported, but wanted to check this in case we go back.
> partial IE11 support

- doc/CHANGES.md
- spec/utils-spec.ts
- src/dragdrop/dd-utils.ts
- src/gridstack.ts
- src/utils.ts
* fix for #1373
* Utils.defaults() now works recursively which was causing sub items to not e init properly.
* also cleaned up some signature calls to TS standards
* you can now have resize handles and still auto-hide them.
> fix setting resize handles to not alwaysShowResizeHandle

- demo/float.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
* fix for #937, thank you @marttop for proposing a fix
* ended up re-writting the CSS creation routine and make it easier to maintain going forward.
* we now only re-create stylesheet when margin or cellHeight (the only static items) change.
Else we happen row based rules as the grids needs them (and only what it needs, not always +10)
> v2: fix to animate

- README.md
- doc/CHANGES.md
- src/gridstack-poly.js
- src/gridstack.ts
explicit drop for IE11 and no longer compile polyfill
(size increase and still issue don't ewarrant such a obsolete support - use 1.x instead).
> v2: explicit IE11 support drop

- doc/CHANGES.md
- spec/utils-spec.ts
- src/gridstack.ts
- src/utils.ts
* fix for #1373
* Utils.defaults() now works recursively which was causing sub items to not e init properly.
* also cleaned up some signature calls to TS standards
* you can now have resize handles and still auto-hide them.
> v2: fix setting resize handles to not alwaysShowResizeHandle

- demo/index.html
- demo/static.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack-dd.ts
- src/gridstack.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
* more complete fix for #858, and #1412
* grid `static: true` to no longer add any drag&drop (even disabled) which should speed things up, and `setStatic(T/F)` will now correctly add it back/delete for items that need it only.
* fixed JQ draggable warning if not initialized
* add `GridStackWidget.html` now lets you add any HTML content when calling `grid.load()`
* added demo showing static/non-static switch for debugging/info
> fix for static grid, enale dragging on fly

- README.md
- demo/advance.html
- demo/anijs.html
- demo/column.html
- demo/float.html
- demo/locked.html
- demo/nested.html
- demo/responsive.html
- demo/serialization.html
- demo/two.html
- demo/vue2js.html
- demo/vue3js.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1155-max-row.html
- spec/e2e/html/810-many-columns.html
- spec/gridstack-spec.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
fix for #1418
* `save(saveContent = true)` now lets you optionally save the HTML content in the node property, with load() restoring it
* `addWidget(opt)` now handles just passing a `GridStackWidget` which creates the default divs, simplifying your code. Old API still supported.
* fixed all demos and test case to use newer API
> save() will now optionally save grid HTML content

- demo/index.html
- demo/static.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack-dd.ts
- src/gridstack.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
* more complete fix for #858
* grid `static: true` to no longer add any drag&drop (even disabled) which should speed things up, and `setStatic(T/F)` will now correctly add it back/delete for items that need it only.
* fixed JQ draggable warning if not initialized
* add `GridStackWidget.html` now lets you add any HTML content when calling `grid.load()`
* added demo showing static/non-static switch for debugging/info
> V2: fix for static grid, enable dragging on fly

- README.md
- demo/advance.html
- demo/anijs.html
- demo/column.html
- demo/float.html
- demo/locked.html
- demo/nested.html
- demo/responsive.html
- demo/serialization.html
- demo/two.html
- demo/vue3js.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1155-max-row.html
- spec/e2e/html/810-many-columns.html
- spec/gridstack-spec.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
fix for #1418
* `save(saveContent = true)` now lets you optionally save the HTML content in the node property, with load() restoring it
* `addWidget(opt)` now handles just passing a `GridStackWidget` which creates the default divs, simplifying your code. Old API still supported.
* fixed all demos and test case to use newer API
> V2: save() will now optionally save grid HTML content

- README.md
- demo/column.html
- demo/responsive.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
* fix for #1338 and likely #1332
* add `LayoutOptions` to `column()` for multiple re-layout options, including 'none' that will preserve the x and width, until out of bound/overlap
* Possible values: 'moveScale' | 'move' | 'scale' | 'none'
* update demos to have dropdown choices, and test cases
> column(n) re-layout options to not scale/move

- demo/column.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
* fix for #1332
* in addition to some pre-built method, you can now have your own callback that is given the column count and nodes for you to modify
* rest of the code will validate and place those items accordingly. you only need to focus on x,y,w,h locations.
* column.html was updated to show usage
> custom column re-layout callback

- demo/static.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- src/gridstack.ts
* fix for 1435
* `class="ui-draggable-disabled ui-resizable-disabled"` have been added back to static grid items, so existing CSS rule to style continue working
* add `data-gs-staticGrid` attribute
> added ui-XYZ-disable style back

- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack.ts
* better fix than #1441 - thanks for suggestion!
* when reisizng we incorrectly use getMargin() which is correctly 'undefined' if all 4 sides don't match
(should had bee using top+bottom but actually  doesn't need any margin, like horizontal)
* fiuxed test cases to check for these scenarios
> fix setting marginTop to break resizing

- src/dragdrop/dd-base-impl.ts
- src/dragdrop/dd-draggable.ts
- src/dragdrop/dd-droppable.ts
- src/dragdrop/dd-element.ts
- src/dragdrop/dd-manager.ts
- src/dragdrop/dd-resizable-handle.ts
- src/dragdrop/dd-resizable.ts
- src/dragdrop/dd-utils.ts
- src/dragdrop/gridstack-dd-native.ts
- src/utils.ts
* make sure to add .ui-resizable-resizing class while resizing, else we fall into CSS 300ms animation (grid default to animate)
resize is now fast like dragging
* removed drag/resize delay timeout - not needed and Util has routine anyway if we decide later
* fixed typos throughout H5 code
* changed credit order to give credit where credit is due (rhlin)
> H5: resizing performance

- demo/two-h5.html
- src/dragdrop/dd-base-impl.ts
- src/dragdrop/dd-draggable.ts
- src/dragdrop/dd-droppable.ts
- src/dragdrop/dd-element.ts
- src/dragdrop/dd-manager.ts
- src/dragdrop/dd-resizable-handle.ts
- src/dragdrop/dd-resizable.ts
- src/dragdrop/dd-utils.ts
- src/dragdrop/gridstack-dd-native.ts
- src/gridstack.ts
- src/index-h5.ts
- src/index-jq.ts
- src/index-static.ts
- src/utils.ts
- webpack.config.js
pushing all H5 changes (with history re-written) to be on top on v2.2.0-dev latest
> H5: rebased from 2.2.0 latest code

- src/dragdrop/dd-base-impl.ts
- src/dragdrop/dd-draggable.ts
- src/dragdrop/dd-droppable.ts
- src/dragdrop/dd-element.ts
- src/dragdrop/dd-manager.ts
- src/dragdrop/dd-resizable-handle.ts
- src/dragdrop/dd-resizable.ts
- src/dragdrop/dd-utils.ts
- src/dragdrop/gridstack-dd-native.ts
- src/gridstack.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
- webpack.config.js
* went through new code for DD and made sure we have a type for everything
* cleanup to match lib style (public vs private)
* made all routines return 'this' for chainable calls. Abstract DDBaseImplement still return :void
otherwise had to do
`return this as unknown as DDBaseImplement`
for all sub-classes which is annoying.
* created DDUIData to hold what we need for callback data. Commented out part we don't use today...
> h5: drag&drop code cleanup

- src/dragdrop/dd-draggable.ts
- src/dragdrop/dd-droppable.ts
- src/dragdrop/dd-resizable-handle.ts
* changed event handlers to be methods, but init to var bindable which is more typescript like (and easier to understand IMO)
* this happened to fix issue dragging between 2 grids not moving obj
> h5: event handler as methods

- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- src/dragdrop/gridstack-dd-native.ts
- src/gridstack-dd.ts
- src/gridstack.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
* always thought it was weird to have a (per) grid option when we had a list of D&D
plugins but last one won.
* now we only have a global static DD that is shared. Grid instance can be infered by element
for any needed options.
> h5: del `ddPlugin` grid option

- src/gridstack.ts
* you can now drag from either grids in two.html to the trash to delete.
html5 native D7D only supports sinlge callback, which si fine for all but the drop to erase target,
gridstack now sets a single callback and tell that grid to update.
> h5: fixed dragging from multiple grid to trash

- demo/advance-h5.html
- src/dragdrop/gridstack-dd-native.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* you can now drag in from two.hmtl toolbar icons (2 of them)
* moved Gridstack internal method to Utils.getElements() to get list of matching items
* dd native uses that to iterate over each API like jqueryUI does.
> h5: GridStackDDNative now support list of items

- src/gridstack.ts
Hey there,
this PR fixes a bug when using the `itemClass` option and dragging an item. The placeholder also needs the default `itemClass` (to be consistent with the behavior of items placed on the grid).
> Fix placeholder not carrying base item class

- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack.ts
- src/index-h5.ts
- src/index-jq.ts
- src/index-static.ts
* all drag&drop grid code has been moved to gridstack-dd.ts (base class for html5 and jquery version)
* that reduces static grid requirements down from 43k to just 35k
* with html5 complete is still 64k (+29k) and jq 187k (+152k)
> h5: moved all DD code to gridstack-dd.ts

- demo/react.html
Add React usage example (replicating the behavior/application in Vue-gridstack.js examples).
> Add react example

- src/gridstack.scss
- src/gridstack.ts
- src/h5/dd-droppable.ts
* html5 code incorrectly adding a style sheet per instance
(and never removing them) for what should be a global style.
> h5: moved the cursor style over to main css

- src/gridstack-dd.ts
* to support html5 D&D we now allow ourself to e a drop target when moving
item around, otherwise we get a 'no drop' cursor the entire move
* we ignore the 'dropover' & 'drop' event so regular 'dragend' will do the right thing.
* tested html5 and JQ version - no apparent side effect
* Note: we still get a very quick flicker to 'no-drop' initially (until
accept routine is called ? not sure how to prevent that.
> h5: prevent no-drop cursor when moving items

- doc/CHANGES.md
- src/gridstack-dd.ts
* fix for #1484, introduced in 2.0.1
* make sure we reset _added flag when leaving other grid and we get back
> fix to drag between 2 grids and back

- demo/react.html
- doc/CHANGES.md
- spec/e2e/html/1471-load-column1.html
- src/gridstack-engine.ts
- src/gridstack.ts
- src/utils.ts
* fix for #1471
* when `load()` is called into a grid that is 1 column mode due to
small area, we now cache the original 12 column layout to restore correctly
* added sample code. Had to change more code than expected.
* Also optimized loading to not re-do some items (re-writing attr multiple times)
* Also fixed react sample
> load() in 1 column mode layout fix

- demo/serialization.html
- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack-dd.ts
- src/gridstack.ts
* fix #1235
* `update(el, opts)` re-write to take all `GridStackWidget` options
(not just x,y,width,height) and do everything efficiently.
* Fixed `locked()`, `move()`, `resize()`, `minWidth()`,etc...
to call update() instead which does all the constrain,
not just update attributes!
* update spec to test, and serialize demo to show improved feature
* OLD api to pass 4 params will work for now (console warning)
> update(el, opts) re-write to take all options

- README.md
- demo/events.js
- demo/knockout.html
- demo/nested.html
- demo/right-to-left(rtl).html
- demo/static.html
- demo/two-jq.html
- demo/two.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
- spec/e2e/html/1142_change_event_missing.html
- spec/e2e/html/1143_nested_acceptWidget_types.html
- spec/e2e/html/1286-load.html
- spec/e2e/html/810-many-columns.css
- spec/gridstack-spec.ts
- spec/utils-spec.ts
- src/gridstack-dd.ts
- src/gridstack-extra.scss
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* removed 'data-' from all attributes (legacy JS style) and shorten width/height to w/h
* make for smaller and more efficient code and CSS.
Easy enough to global replace in your code.
> 'data-gs-min-width' to 'gs-min-w' attr rename

- README.md
- demo/advance.html
- demo/anijs.html
- demo/column.html
- demo/events.js
- demo/float.html
- demo/knockout.html
- demo/locked.html
- demo/nested.html
- demo/react.html
- demo/responsive.html
- demo/right-to-left(rtl).html
- demo/serialization.html
- demo/static.html
- demo/two-jq.html
- demo/two.html
- demo/vue2js.html
- demo/vue3js.html
- doc/README.md
- spec/e2e/html/1155-max-row.html
- spec/e2e/html/1471-load-column1.html
- spec/gridstack-engine-spec.ts
- spec/gridstack-spec.ts
- spec/utils-spec.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/h5/dd-draggable.ts
- src/types.ts
- src/utils.ts
* just like the attributes shortening, Grid Item position are now
x,y,w,h with shorter min/maxW|H
* this and prev change end up saving 2k on gridstack-h5.js output file!
(now only 63.2k)
* hard to change as not simple global replace, as width|height are still
used in CSS and rect, etc....
> GridStackWidget use w,h,minW,minH

- README.md
- doc/CHANGES.md
- src/gridstack.ts
* doc for v3 release
* also fixed old api that call update()
> doc for v3 release

- demo/nested.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- src/gridstack.ts
- src/types.ts
* added new API to create a grid and it's children
* load() will now recursively create nested grid
* updated nested.html to use new API
* fixed tests
TODO: next have save() work on nested grids (API will have to change)
> new addGrid() method to create a grid + children

- demo/nested.html
- demo/serialization.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- spec/utils-spec.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* `save()` will now work recursively saving nested grids
options and children.
* `save()` can now be used to save the current grind full options + children
so you can call `static addWidget()`
to re-create everything
* `destroy(`) now clears memory usage (fix circular dep)
more for #1498
> save() works on nested grids

- demo/nested.html
* turns out #1499 works just fine (was mistaken) but updated demo to say
we're using JQ version for that one.
> nested.html using jq version

- src/h5/gridstack-dd-native.ts
Handle ddResizable enable/disable just like ddDraggable. Fixes #1505
> HTML dnd check for setup ddResizable before enable/disable

- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
- src/h5/gridstack-dd-native.ts
* fix for #1505
* make sure we don't call  movable()/resizable() on locked items to start with
* prevent staticGrid from having enable/disable state changes as well
* better doc
> don't call movable()/resizable() on locked items

- README.md
* link to issue #465 so it can be found
> added knockout links

- doc/CHANGES.md
- spec/e2e/html/1419-maxrow1-cant-insert.html
- spec/gridstack-engine-spec.ts
- spec/gridstack-spec.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
* dragging into a fixed row grid works better
(check if it will fit, else try to append, else won't insert)
**** **possible BREAK** (unlikely you will use engine directly)
* engine constructor takes Options struct rather than spelling arguments (easier to extend/use)
* `canBePlacedWithRespectToHeight()` -> `willItFit()` like grid method.
> dragging into a fixed row grid

- src/h5/dd-resizable.ts
* we were incorrectly restoring el properties in _cleanHelper()
(found whiledebugging code)
* added missing types
> h5: fix to restoring resize properties

- doc/CHANGES.md
- spec/e2e/html/1330-maxw-left-resize.html
- src/gridstack-dd.ts
- src/h5/dd-resizable.ts
fix #1330
* we now set maxWidth/maxHeight to prevent grid item from resizing past their size
* fixed code to prevent item from moving left when they reach max width
* added sample test case
> W side resize and maxW fix

- demo/two.html
- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
* fix #1472
* drag over now loads all widget attributes if we don't have a node
(dragged from toolbar)
> support all options for new dragged in widgets

- doc/CHANGES.md
- spec/e2e/html/1511-drag-any-content.html
- src/h5/dd-draggable.ts
* fix #1511
* you can now click any grid item content and drag away
* added sample test case
> h5: drag fix

- src/gridstack.ts
* make sure to insert not append on load() since we reserves sort
so ODM order matches visual order.
> load() DOM order fix

- demo/index.html
- demo/react-hooks.html
- doc/CHANGES.md
Added an example do the demos folder using React hooks and a controlled, functional component.
> Added example using a controlled React component and hooks. #735

- doc/CHANGES.md
- spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
- spec/e2e/html/1535-out-of-order.html
- src/gridstack.ts
* fix #1535
* make sure to call batchUpdate() on init load to preserve gs-y values
> call batchUpdate() on init load

- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
- src/h5/dd-draggable.ts
- src/h5/dd-utils.ts
* fix #1540
* DragEvent is not defined on Safari (regular MouseEvent + dataTransfer field)
so fixed initEvent() to not use `instanceof DragEvent` but copy fields
* according to spec (and required by Safari) the drag image has to be visible in
the browser (in dom and not hidden) so make it a 1px div
(this also helps chrome not showing a no-drop target cursor on Mac)
* more DD code cleanup
> H5 safari drag fix

- doc/CHANGES.md
- spec/e2e/html/1545_disable_move_after.html
- src/gridstack-ddi.ts
- src/h5/dd-draggable.ts
- src/h5/dd-resizable.ts
* fix #1545
* make sure to remove event handlers when disabling move
* constructor now calls enable(), and destroy calls disable() to centralize call
> fix to disableMove()

- doc/CHANGES.md
- src/h5/dd-resizable-handle.ts
* fix #1546
* re-wrote rhlin resize code to no longer do a delay in adding move and up events.
not sure why he had 100ms + 300ms delays causing race conditions...
* also fixed so we clean up correctly
* also resize won't happen unless you move 3 pix now (was 1)
> fix resize delay causing potential error msg

- src/gridstack-dd.ts
- src/h5/dd-resizable.ts
- src/utils.ts
As discussed in #1001 the resizing with scrolling is not working.
I'm trying to solve it here but I'm having some troubles. Now is working fine but I'm resizing the layout adding some rows on `resizestart` because when while resizing an item there is a back and force with the number of cells creating a strange behaviour.
> Resizing issue

- doc/CHANGES.md
- src/gridstack-dd.ts
* fixed no-drop cursor on windows when dragging within a default grid (no external drag in)
> fixed no-drop cursor on windows

- doc/CHANGES.md
- src/h5/dd-draggable.ts
fix for #1541
* on Safari we had a delay due to a 300ms+ animating back to old location on drop.
'dragend' wasn't called (what we use) until that animation was done.
to fix that had to call `preventDefault()` during drag
https://stackoverflow.com/questions/61760755/how-to-fire-dragend-event-immediately
* for that to work I ALSO had to remove `{passive: true}` when adding the drag event, so passing just 'true' for grabing event
NOTE:  I noticed Safari doesn't auto-scroll the grid (didn't before), but chrome Mac does.
html5 drag event is painfully incompatible between browsers...
> H5 Safari fix delay when dropping

- src/gridstack.ts
tweak to saving nested grids with content
> tweak to saving nested grids with content

- README.md
- doc/CHANGES.md
- spec/e2e/html/1572_one_column.html
- src/gridstack.ts
* fix for #1572
* we now automatically add `.grid-stack-N` class when user specify column: N option for CSS to work.
> column-N class fix

- doc/CHANGES.md
- spec/e2e/html/1571_drop_onto_full.html
- src/gridstack-dd.ts
- src/h5/dd-droppable.ts
* fix #1571
* dragenter checks for full grid using `willItFit()` before accepting an item
* also cleanup h5 dd-droppable to not add listner or remove them uncessarly.
> don't allow drop when grid is full

- doc/CHANGES.md
- spec/e2e/html/1570_drag_bottom_max_row.html
- spec/e2e/html/1572_one_column.html
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/utils.ts
better drag-out/in from below heuristics
* fix #1570
* we now have code to check if dragging outside of the grid (`engine.isOutside()`) which
checks for items past maxRow or added as last row in a real position vs being dragged out.
fix cellHeight() updating CSS for # of rows
* fix #1579
* make sure to re-create the CSS with actual number of rows needed when changing cell heights
*
> better drag-out/in from below, cellHeight() CSS fix

- doc/CHANGES.md
- spec/e2e/html/1581_drag_by_header_h5.html
- src/h5/dd-draggable.ts
* fix #1581
* set `draggabble` to actual div handle rather than entire item so content can also respond to dragging.
* no longer need to have` mousedown` to check for click on actual drag area...
* added demo test
- [X Created tests which fail without the change (if possible)
> H5 draggable by actual div handle

- demo/two-jq.html
- doc/CHANGES.md
- package.json
- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack-engine.ts
- src/gridstack-extra.scss
- src/gridstack.scss
- src/gridstack.ts
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-element.ts
- src/h5/dd-manager.ts
- src/h5/dd-resizable-handle.ts
- src/h5/dd-resizable.ts
- src/h5/dd-utils.ts
- src/h5/gridstack-dd-native.ts
- src/index-h5.ts
- src/index-jq.ts
- src/index-static.ts
- src/jq/jquery-ui.js
- src/types.ts
- src/utils.ts
* getting jquery-ui from website again now that it is working
* no code change per say (indent and comments) but also no longer need to comment out
> AMD. Register as an anonymous module.
* updated two-jq.html to show actual $ usage for testing
> @adumesny https://jqueryui.com/download/ version

- Gruntfile.js
- README.md
- demo/advance.html
- demo/index.html
- demo/mobile.html
- doc/CHANGES.md
- doc/README.md
- src/jq/gridstack-dd-jqueryui.ts
- src/jq/jquery.ui.touch-punch.js
- src/types.ts
- webpack.config.js
* fix #1413 #444
* we are now using the latest v1.0.8 touch-punch branch from
https://github.com/RWAP/jquery-ui-touch-punch
and compiling in JQ version (only 188k -> 190k) so mobiles work out of the box
* HTML5 v3+ does not currently support `touchmove` events. This will be added in a future release.
* added a mobile.html demo showing usage, updated doc/readme
> support mobile in jq version out of the box

- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
* we now create the placeholder content (2 div with optional text)
on the fly as needed.
* moved more DD code to gridstack-dd.ts
> create placeholder divs on the fly

- demo/nested.html
- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
* fix #1538
* we now call resize on nested grids when window changes size
* we also call nested grid of the currently being resized item as it happens (live)
* updated nested.html to show more complete case, with custom column and different oneColumn constrain
> loding nested grids small then growing

- doc/CHANGES.md
- spec/e2e/html/1330-1559-left-resize-maxW-and-others.html
- src/h5/dd-resizable.ts
> H5: resize from left side can move item right

- demo/responsive.html
- demo/two.html
better responsive demo
* use viewport % cellHeight to make items square but not require CSS update
(vs 'auto' which does re-create on every resize)
> better responsive demo

- src/gridstack.ts
grid-stack-items does not keep their respective DOM order if x,y declarations are missing (autoPosition) in Firefox.
The array sort order is implementation-defined if their is not a consistent comparison function for the elements of items:
https://tc39.es/ecma262/#sec-array.prototype.sort
Following simple example shows an reversed order of the grid-stack-items in Firefox than they appear in the DOM:
https://jsbin.com/yitiputuqe/1/edit?html,output
> Add array sort compareFunction to keep items respective DOM order in Firefox

- src/gridstack.ts
- src/types.ts
Creates a shared GridStackEventHandlerCallback type and updates the event handler callback signature to account for optional helper parameter
- [] Extended the README / documentation, if necessary
> fix event handler callback signature

- doc/CHANGES.md
- spec/e2e/html/141_1534_swap.html
- spec/e2e/html/141_swap_old.html
- spec/gridstack-engine-spec.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
big overall of the collision detection code - you can now:
* swap items of same size vertically/horizontally when grid is full (`maxRow`)
**this has been 5.5years in the making and the most asked question**
It is now also the default in `float:false` as it feels more natural than pushing new row
(could add Alt-key to get either behavior of push vs swap ?)
* moving items down or up behave the same way (used to have to push WAY past to insert after)
* optimized the collision code to not do extra work multiple times and only check
if change and not tried before
* heuristics now checks for >50% past the grid mid point (taking margin into account)a
TODO part II:  handle mid point of dragged over items rather 50% of row/column
and check for the most covered when multiple items collide.
* fix …
> collision overall - support for swap

- demo/events.js
- doc/README.md
- src/gridstack-dd.ts
- src/gridstack.ts
Added an on resize listener to get the size of the node while resizing
- [] Created tests which fail without the change (if possible)
> Add resize event listener

- demo/events.js
- doc/CHANGES.md
- doc/README.md
- src/gridstack-dd.ts
fixes to #1616 for new `drag|resize event` - only call when they change.
Updated docs
> drag | resize events tweaks

- src/gridstack-engine.ts
- src/types.ts
in order to improve #1094 behavior, we may now do a partial repack after we moved an item below
keeping the original wanted location so we can try again
and push items out of the way.
> collision: re-pack in middle of collision

- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
* re-write on how dragging new objects in from the outside works.
It now re-uses the same drag collision code as in place,
so we check for 50% coverage and all that good stuff, with full helper
size info boundaries instead of the old way of mouse
cursor -> cell mapping.
> Collision: part3 making drop-in rewrite

- src/gridstack-dd.ts
- src/gridstack-engine.ts
fix dragging long items from outside (ex two.html) - we now constrain to fit in grid as dragout event will tell us when we leave (not shape but cursor event)
> collision: fix dragging long items from outside

- demo/two.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack-dd.ts
- src/gridstack.ts
* add `GridStack.setupDragIn()` so user can update external
draggable after the grid has been created.
* you can pass in new selector and options, else it uses the grid last option values.
(called on during init() but may be needed when items change dynamically).
* safe to call multiple times and on already draggable items
* fix #1637
> grid.setupDragIn()

- demo/column.html
- doc/CHANGES.md
- src/gridstack.ts
* fix changing column # `column(n)` now resizes `cellHeight:'auto'` to keep square
* update column.html demo to have fix cellHeight (makes it easier to see relayout for debugging)
> column # changes auto cellHeight

- demo/column.html
- spec/e2e/html/141_1534_swap.html
- src/gridstack-engine.ts
more for #1094
* dragging larger size items will now correctly recursively push items down
one after another
* also fixed swap to check for touching items
> collision: more fixes

- spec/e2e/html/141_1534_swap.html
- src/gridstack-engine.ts
- src/utils.ts
swap() now handles objects taking same columns (but different height)
as a simple swap (no further collision)
which optimizes current flow.
more #1094
> collsion: restored place across

- README.md
- demo/two-jq.html
- demo/two.html
- demo/web2.html
- doc/CHANGES.md
- spec/e2e/html/1570_drag_bottom_max_row.html
- spec/e2e/html/1571_drop_onto_full.html
- spec/gridstack-spec.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/h5/dd-utils.ts
- src/types.ts
- fix #393 #1612 #1578
- re-write of the **drag in/out code - fixing 5 years old bug**
1. we now remove item when cursor leaves (`acceptWidgets` case using `dropout` event) or shape is outside (re-using same method) and re-insert on cursor enter (since we only get `dropover` event). Should **not be possible to have 2 placeholders** which confuses the grids.
2. major re-write and cleanup of the drag in/out. Vars have been renamed and fully documented as I couldn't understand the legacy buggy code.
3. removed any over trash delay feedback as I don't see the point and could introduce race conditions.
> drag in/out re-write

- demo/vue3js.html
To make the difference between Vue 2 and Vue 3 even clearer, perhaps using the Composition API would be a good idea. I stumbled across this because I only started learning Vue with version 3.x, so the Composition API is more familiar to me than the Vue 2 approach. I could imagine that people often feel this way and therefore maybe both approaches could be covered to save time in translation.
I started a new PR because my branch got a little messy. I hope that the spacing and line ending is fine this time ^^
> adding vue 3 composition api

- LICENSE
- demo/two.html
- doc/CHANGES.md
- package.json
- spec/e2e/html/141_1534_swap.html
- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack-engine.ts
- src/gridstack-extra.scss
- src/gridstack-poly.js
- src/gridstack.scss
- src/gridstack.ts
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-element.ts
- src/h5/dd-manager.ts
- src/h5/dd-resizable-handle.ts
- src/h5/dd-resizable.ts
- src/h5/dd-utils.ts
- src/h5/gridstack-dd-native.ts
- src/index-h5.ts
- src/index-jq.ts
- src/index-static.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
- src/utils.ts
fix #1094
* found I needed to take entire row (not just new location) when doing collision to correctly push down bottom items first so they keep their order and prevent large objects from leapfrogging smaller ones.
(like old code used to do)
* removed _beforeDrag and _packY fields and re-use existing _orig position data which simplifies things
* removed yOffset during _fixCollisions() as it was incorrect (reverse sorting should take care of that)
* on _leave() of external item, we now restore all items to original position using restoreInitial() (prevents any error from sticking)
NEEDLESS to say, this is MUCH more complicated than the old _fixCollision() that moved to new loc then pushed anything down in that row and below (bottom first) which is dead simple... but required you to move …
> collision: more edge case fixes

- demo/nested.html
- doc/CHANGES.md
- package.json
- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-element.ts
- src/h5/dd-manager.ts
- src/h5/dd-resizable-handle.ts
- src/h5/dd-resizable.ts
- src/h5/dd-utils.ts
- src/h5/gridstack-dd-native.ts
- src/index-h5.ts
- src/index-jq.ts
- src/index-static.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
- src/utils.ts
fix #1661
* fix error when clearing default options
* fix to not save list of children options
* nested demo now has save/clear/load to verify all works fine.
> serialization of nested grid

- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
fix #1669
now pass the original element around, as `node.el` is the placeholder during resize
(which doesn't have resize handlers)
> JQ resize fix

- README.md
- demo/react-hooks.html
- demo/react.html
- demo/vue2js.html
- demo/vue3js.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
* removed the old stale 'master' branch and renamed 'develop' active one to standard 'master' branch
If you have a local clone, you can update it by running:
```js
git branch -m develop master
git fetch origin
git branch -u origin/master master
```
> develp -> master branch rename

- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1658_enableMove.html
- spec/gridstack-spec.ts
- src/gridstack-dd.ts
- src/gridstack.ts
- src/h5/gridstack-dd-native.ts
* fix #1658
* we now set the grid options BEFORE we update each item as that override
* `enableMove()` and `enableResize()` no longer take a second optional param as we must set grid options for things to work
(if you want to enable current items but not change the grid itself, there is already the `movable('.grid-stack-item')` method that doesn't change the grid (no need for 2 ways)
* did some more cleanup and added test case.
> enableMove() fix

- demo/two-jq.html
- demo/two.html
- demo/web2.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1143_nested_acceptWidget_types.html
- spec/e2e/html/1419-maxrow1-cant-insert.html
- spec/e2e/html/1571_drop_onto_full.html
- spec/e2e/html/1658_enableMove.html
- src/h5/dd-draggable.ts
- src/types.ts
* fixed h5 case when helper is function to correctly call it with event
* updated two.html (and jq) demos to show it.
> H5: fix dragInOption clone: myFunc()

- doc/CHANGES.md
- spec/e2e/html/141_1534_swap.html
- src/gridstack-dd.ts
fix #1679
* 4.x broke the left side size handle (as it needs to move item as well as resize)
now works again and should be more solid too.
> collision: Resizable: {handles:'w/sw'} fix

- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
> addGrid() checks for nested '.grid-stack' div

- doc/CHANGES.md
- spec/e2e/html/1693_load_after.html
- spec/gridstack-spec.ts
- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack-engine.ts
* fix #1693
* broke in 4.x. load() now correctly works again (batch mode saving initial values multiple times)
* added unit test and demo as well, so this shouldn't happen again.
> collision: `load` after `init()` fix

- demo/index.html
- demo/two_vertical.html
- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/utils.ts
* fix #1687
* broken in 4.x - dragging between 2 grids with `maxRow/row` set
* `willItFit()` could modify the passed in node (with new algorithm) instead of making a clone copy to check if it fits.
* added a new vertical grid demo (which has known issues documented)
* added unit test
> collision: `row / maxRow` drag 2 grids

- doc/CHANGES.md
- spec/e2e/html/141_1534_swap.html
- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
* fix #1676
* simplified the code so cursor is what make items leave/enter (else we can get double shadow)
* no longer need `engine.isOutside()` (we use cursor leave event)
or `_isCursorOutside` (use `_temporaryRemoved`)
* we also always use 'dropover'/'dropout' to track when we enter/leave to be consistent between multi grids and single one that doesn't accept widgets
(instead of sing acceptWidgets flag)
> collision: fix for single grid drag out/in

- demo/two_vertical.html
- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack-engine.ts
- src/types.ts
* fix #1687
* willItFit() will now save the location we can be added to, which is used upon inserting.
> collision: final 2 grids with maxRow

- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.ts
fix #219
**fixing another 6 years old request**
* we now automatically insert extra rows
when dragging an item at the bottom below others to make it easier to insert below.
* added `_extraDragRow` to grids driven by dragged item
- [] Created tests which fail without the change (if possible)
> insert extra rows, insert below

- README.md
- doc/CHANGES.md
- src/jq/gridstack-dd-jqueryui.ts
- webpack.config.js
* fix #1709
also fix #1306 I believe.
* correct info in Readme for using JQ version and ES6 (tested in Angular app)
* changed .ts to include jquery by name instead of location.
> JQ version and ES6

- doc/CHANGES.md
- package.json
- spec/e2e/html/1704_scroll_bar.html
- src/gridstack-dd.ts
- src/gridstack-ddi.ts
- src/gridstack-engine.ts
- src/gridstack-h5.ts
- src/gridstack-jq.ts
- src/gridstack-poly.js
- src/gridstack-static.ts
- src/gridstack.scss
- src/gridstack.ts
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-element.ts
- src/h5/dd-manager.ts
- src/h5/dd-resizable-handle.ts
- src/h5/dd-resizable.ts
- src/h5/dd-utils.ts
- src/h5/gridstack-dd-native.ts
- src/jq/gridstack-dd-jqueryui.ts
- src/types.ts
- src/utils.ts
- yarn.lock
fix #1704
* introduced in 4.x, 'dropover' no longer checks for document.documentElement.scrollTop
since we call getBoundingClientRect() which handles being scrolled already.
> scrollbar fix

- demo/nested.html
- doc/CHANGES.md
- src/gridstack.ts
* fix #1682
* updated nested demo to show adding nested grid
> `addWidget()` now supports recursive grids

- demo/responsive.html
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* fix #1655
* `addWidget()` while in 1 column now remembers original wanted width
(saves in 12 column layout)
* removed uneeded _oneColumnMode (check for opts.column === 1)
* updated responsive demo to add a 4x1 widget
(test while in 1 column, size up back to 12 column)
> `addWidget()` while in 1 column fix

- doc/CHANGES.md
- src/jq/gridstack-dd-jqueryui.ts
* fix #1700
* jquery DD wrapper now correctly returns status to callee,
to prevent parent grid to also handle drag event
* exposed in 4.0.3 but issues was much older.
- [x All tests passing (`yarn test`)
> JQ nested grid drag

- doc/CHANGES.md
- src/gridstack.scss
* fix #1678
* make sure we set CSS rules for gs-x:0 and not just 1+
* turns out this never worked as file always did 1-12 styles.
> item gs-x:0 not animating fix

- spec/e2e/html/1727_resize_scroll_top.html
- src/utils.ts
when scroll element does not start from top of page, the scrolling during resize does not work as expected, the decision if to scroll, and amount to scroll, is computed wrong.
This PR fixes this.
- [x ] All tests passing (`yarn test`)
> fix resize-scroll when gridster is not at top of page

- src/gridstack-dd.ts
- src/h5/dd-droppable.ts
This should fix #1684 
In Safari, relatedTarget is null, causing the `dragleave` event to fire the `dropout` event early. To detect if we've actually dropped out, I've added a check to make sure the node has the `_temporaryRemoved` prop set. There was similar logic in place in the `dropout` event in v3 so this might have been the fix for that.
I've also tested that this is still working in Chrome and Edge, but was having issues trying to run the local build on Firefox
Current behavior
With fix
> fix Safari bug with dropping element inside grid

- doc/CHANGES.md
- src/utils.ts
fix #1562
* changed to use document.scrollingElement
as topmost element, which seem correct and required by safari.
> Safari mac: fix scrolling

- spec/e2e/html/1727_resize_scroll_top.html
- src/utils.ts
fix for issue #1745 
looks like browsers are quirky beyond believe.
The properties .clientHeight and .getBoundingClientRect() are inconsistent for regular elements compared to the outmost 'html' element.
Hope you don't mind the verbose comment, and sorry for being late to look at this problem.
Have also enhanced test file covering previous problem of #1727 to contain an additional scrollbar on html element to see any adverse effects, of course such scrollbar defeats the concept of automatically scrolling while user drags something, since you don't know what needs to be moved.
> fix scroll problem when scrollbar on html element

- doc/README.md
Fixed the link to the main site of grid option RTL example in documentation.
> Fixed doc RTL link example

- demo/float.html
- doc/CHANGES.md
- spec/gridstack-engine-spec.ts
- src/gridstack-dd.ts
- src/gridstack-engine.ts
* fix #1767
* `locked` item can be user moved/resized just not pushed by other nodes (broke in 1.1.1)
* had incorrectly assume locked = noMove + noSize (user driven) but it's for layout only, so now you have complete choice.
> `locked` item can be moved/resized

- doc/CHANGES.md
- src/gridstack.ts
* fix #1764
* don't force static grid when deleting content (was incorrectly setting attribute as part of cleanup)
> destroy(false) doesn't force static grid

- .eslintrc.js
- package.json
- src/gridstack-dd.ts
- yarn.lock
* changed the GridStack D7D methods to have
func(this: gridStack,..)
as first param, so we can get code-hint again when typing code...
* but now we get warning about private method access,
we can disable all checking with
// @ts-nocheck
which might be bit drastic.
* or use // @ts-ignore instead for each line)
**** requires TS 3.7+ (was on 3.6.5 due to some packaging for older TS issues)
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#ts-nocheck-in-typescript-files
> TS 3.7+ to support @ts-nocheck

- doc/CHANGES.md
- src/gridstack-dd.ts
fix #1784
* `removable:true` by itself (without `acceptWidgets:true`) will now you remove items by dragging them out.
> fix removeable:true by itself now works

- src/h5/dd-draggable.ts
This change will immediately set the initial position of the external helper, it will fix:
* issue shown in [this video](https://www.loom.com/share/904ac32dd4b44c37a60485567e85cf5e)
* by setting the correct initial `y` position of the helper, could skip unnecessary looping in `_packNodes()`
The added "fixed" position will fix the scrollbar issue when the body/container height is set to 100% (relative to window height).
> quickly set external helper initial position + fix scrollbar issue

- demo/nested.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack-engine.ts
- src/gridstack.ts
* fixed documentation for save()
fix #1795
> better save() doc

- demo/float.html
- demo/nested.html
- demo/serialization.html
- doc/CHANGES.md
- doc/README.md
- spec/gridstack-spec.ts
- src/gridstack.ts
- src/utils.ts
fix #1795
* save(false) will no longer have .content field
fix #1782
* save(false, false) now correctly saves nested grids and not actual data structure
* updated demos and test cases for these
> save(false, false) fixes

- doc/CHANGES.md
- spec/utils-spec.ts
- src/gridstack.ts
- src/utils.ts
#fix 1793
* `save(false, true)` followed by enable() throws error.
* we now have new `Utils.cloneDeep()` (needed for grid options) and added test cases.
> save(false, true) + enable() error fix

- src/gridstack-engine.ts
Provides a fix for https://github.com/gridstack/gridstack.js/issues/1835
Explanation:
When going from 12 -> 1 column, this function is run after the node has already had its width set to 1 (I will admit I don't understand the order of events perfectly, this is just what I observed). So when `node.minW` has a value, this condition overrides the node width to be larger than the column count. 
The behavior in #1835 is from a few lines down, where now the condition for `node.w > this.colum`  passes and causes the layout to be cached which was only intended to run when starting from 1 and going to 12.
> Don't override node width when switching column mode

- demo/serialization.html
- doc/CHANGES.md
- src/gridstack.ts
* loading grid will now handle `cellHeightUnit` being set (what happens on save)
rather than only '10rem' example
* changed save/load demo to use rem sizing
> #1794 fix rem unit size for save+reload

- src/gridstack.scss
See issue gridstack#1853 for details.
In summary: this proposed change aligns the -sw grid-item sizing icon to have the same 4px bottom as its -se variant. I can confirm this works on Chrome, Edge and Firefox with no performance issues.
> Removed "bottom: 0" from ".ui-resizable-sw"

- doc/CHANGES.md
- src/utils.ts
fix #1860 which was caused by #1793
* cloneDeep() will now skip clonning internal known objects we don't serialize (and delete later with removeInternalAndSame())
> nested grid save inf loop fix

- Gruntfile.js
- README.md
- demo/two.html
- doc/CHANGES.md
- package.json
- src/gridstack-extra.scss
- src/gridstack.scss
- yarn.lock
fix for #1859 using the latest dart-sass
> use dart-sass

- Gruntfile.js
- README.md
- demo/web1.html
- demo/web2.html
- doc/CHANGES.md
- package.json
- src/gridstack-poly.js
- src/gridstack.ts
- src/utils.ts
* some cleanup and documentation for #1887 for IE
> more IE support

- demo/column.html
- doc/CHANGES.md
- spec/e2e/html/1785_column_many_switch.html
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* guard against 0 column
* making changes in a layout, propagates the differences to larger layout (deleting smaller ones)
causing potential negative (x,y) cached values.
We always used nodeBoundFix() to prevent that when adding the nodes back, but due to saving _orig value after (instead of early) and combination of _dirty, we didn't always updating collision in the DOM
* also changed updateNodeWidths() to always scale things down live (regardless of cached layout to make it smoother) but use the largest 12 column layout to scale things up if not already cached.
* more efficient in updating _dirty only nodes attributes from last values.
* added test file showing issue.
> fix #1785 switching column overlap

- doc/CHANGES.md
- spec/e2e/html/1858_full_grid_overlap.html
- src/gridstack-dd.ts
- src/gridstack.ts
- src/types.ts
* also fixed some doc and added test case for another bug
> fix #1890 exception when draggin fast

- doc/CHANGES.md
- src/h5/dd-draggable.ts
- src/h5/dd-resizable.ts
* fix to make #992 better going forward as I'm focusing on nested grids again
* dragging sub item between grids no longer get clipped by parent
* removed basePosition.aboslute option as I'm not sure how we can make it work
(parent has position.relative which will clip us otherwise)
* nested.html you can drag pink items between grids (h5 case, JQ still clipps)
> dragging nested items no longer clipp

- src/h5/dd-draggable.ts
* #1902 change caused a flicker when item goes position fixed, so make sure we position on screen during init as well.
> dragging clipp fix part II

- demo/nested.html
- doc/CHANGES.md
- spec/e2e/html/1558-vertical-grids-scroll-too-much.html
- src/gridstack-dd.ts
- src/gridstack.scss
- src/h5/dd-droppable.ts
- src/h5/dd-utils.ts
- src/types.ts
- src/utils.ts
* fix #992
* we now support dragging into and out of nested grids from parents
* nested.html was updated to showcase this, settings all grids to accept the same widgets. using CSS to differentiate nested items vs not for styling/demo purpose only.
* tested nested, float nad two.html - all seem to continue working (this was a lot of work to fine tune)
* also fix #1558 as we no longer cache the grid position (as we may move when items are placed elsewhere) but get it on every move to reflect latest data
Thank you [@arclogos132](https://github.com/arclogos132) for sponsoring it.
> nested grid in/out drag from parent support

- src/gridstack-dd.ts
- src/gridstack.ts
- src/h5/dd-droppable.ts
* remaining fix for #992 to prevent a nested grid from going inside another until we can do the right thing down the line. Very broken otherwise
* also fixed heuristics to work like regular items (ignore enter/leave for sub grid dragging)
> prevent double nesting using gesture

- demo/nested.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
- src/types.ts
* part of #1009
* we now have a new `column:'auto'` option which is used for nested grids to column size themselves to match their container (same # of column)
This make sure outside and inside items stay the same size
* this will eventually be required when creating grids on the fly dynamically (as good default)
* updated nested.html to showcase this
> nested grid column:'auto' option

- demo/nested.html
- src/gridstack.ts
* fixed issue in nested.html where we had scroll bar when we shouldn't.
* the old code used to set rows # to match the grid min-height (incorrectly when set to say 100% or 10rem) which we no longer do. setting an explicit height (in code) with min-height (in CSS) works just fine.
* `getCellHeight()` will no longer compute using entire grid / #row, but use the first row instead...
> no longer force rows for min-height

- README.md
- demo/custom-engine.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
* add `GridStack.registerEngine()` to let user use their own custom layout engine subclass.
* Thank you [Thomas] for sponsoring it
> add `GridStack.registerEngine()`

- README.md
- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* renamed to be much clearer, added support for old field value (JS only) to not break binary compatibility
* fix #1937
> grid option minWidth -> OneColumnSize

- spec/gridstack-engine-spec.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-resizable-handle.ts
- src/h5/dd-resizable.ts
- src/h5/gridstack-dd-native.ts
* changed private to protected so subclasses can access full implementation of base classes.
* more cleanup on the engine (_notify() second param was removed as never used, Layout per column uses Node types instead), doc tweaks, etc...
- [] Extended the README / documentation, if necessary
> private --> protected

- README.md
- doc/CHANGES.md
- package.json
- src/jq/jquery-ui.js
- yarn.lock
> updated jqueryui to latest v1.13.1

- demo/react-hooks.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/810-many-columns.html
- spec/gridstack-engine-spec.ts
- spec/gridstack-spec.ts
- src/gridstack-engine.ts
- src/gridstack-h5.ts
- src/gridstack-jq.ts
- src/gridstack-static.ts
- src/gridstack.ts
- src/utils.ts
* added batchUpdate(false) to replace commit()
* also updated doc
> added batchUpdate(false) to replace commit()

- demo/nested-jq.html
- src/gridstack.ts
- src/h5/gridstack-dd-native.ts
- src/types.ts
* partial work to get jq nested grid to work #1998, but big issue remain.
just testing example with initial workaround - just to get items to not clipp on drag
overflow-x: hidden causes item clipping (see demo notes)
> partial jquery nested grid workaround

- demo/nested.html
- demo/static.html
- demo/two-jq.html
- demo/two.html
- doc/CHANGES.md
- src/gridstack-dd.ts
- src/gridstack.scss
- src/h5/dd-base-impl.ts
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-manager.ts
* part 1 of #1757
* converted previous HTML5 `draggable=true` based code to simple mouse move/enter/leave events for dragging (like sizing) in preparation of mobile support.
* modified example to help debug issues
* tested to be on par with prev code on Chrome, minus custom cursors.
> mouse event rewrite of draggable=true

- demo/two.html
- package.json
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-manager.ts
- src/h5/touch.ts
Part II for #1757
* added support for mobile touch events, and tested two.html to work great on Android 10 Chrome - dragging between grids and insert/remove
TODO: do sizing (though handle. idealy we could support 2 finger at a later time ! :)
> mobile touch support (dragging)

- demo/mobile.html
- demo/nested.html
- src/h5/dd-draggable.ts
- src/h5/dd-resizable-handle.ts
* part III of #1757
* resizing now works on mobile in h5 - the last step to get fully functional mobile support.
* updated demos to showcase mobile better (ore to do)
TODO: test nested grid as there appears to be a remaining corner case to fix...
> mobile resizing

- demo/nested.html
nested demo: added debug event handler (based on customer Question on Slack)
> nested demo: added debug event handler

- demo/nested.html
- src/gridstack-dd.ts
- src/gridstack.scss
- src/h5/dd-draggable.ts
- src/h5/dd-droppable.ts
- src/h5/dd-resizable-handle.ts
- src/h5/touch.ts
more mobile fixed for #1757
* turns out window.TouchEvent=true on windows 10 Chrome, so don't use it to detect `isTouch` as we were getting double enter/pointerEnter events
* some fix to draggable (desktop tested)
* placeholder is not a 10% black shadow (easier to see than dashed outline)
TODO: in nested.html dragging to other and back to different spot goes to original not dropped location.
Apparently the flow is very different from draggable for nested grids... need more work.
> more mobile fixes: `isTouch` was true on Win10

- src/dd-draggable.ts
- src/dd-droppable.ts
- src/dd-resizable-handle.ts
- src/dd-resizable.ts
- src/gridstack.scss
* desktop fixes for #1757
* fixed resize inside nested grid sending event to parent (for a drag) as well
* fixed long standing issue that nested items how resize handle as well as parent (prevent event from bubbling up)
* fixed dragging out of sub-grid and back into a different spot going initial location instead
> drag & drop Desktop nested fixes

- README.md
- demo/mobile.html
- demo/nested.html
- demo/website.html
- doc/CHANGES.md
- doc/README.md
- src/dd-gridstack.ts
- src/dd-touch.ts
- src/gridstack.ts
- src/types.ts
* `alwaysShowResizeHandle` now support `'mobile'` which is the default, making it much easier (see doc)
everything seems to be working now, just need to release next #1757
* tested on:
Win10: Chrome 104, Firefox 103, Edge 104
Android 10: Chrome
> mobile support tweaks

- .gitignore
- src/gridstack.ts
Sync the Grid's options with the float value.
I also set to check if the value actually changed before calling `triggerChangeEvent`, but maybe this is not desired?
> update Grid's options when setting float

- demo/float.html
- src/dd-gridstack.ts
- src/dd-manager.ts
- src/dd-resizable.ts
* fix for #2018
* resizable _mouseOver() no longer calls event.stopPropagation() (which seems like the right thing to do) but relies instead on DDManager to track our active item
> v6 mouse events and React

- doc/CHANGES.md
- src/dd-resizable.ts
> `removeWidget()` breaking resize handle feedback

- doc/README.md
Change onColumnMode to oneColumnMode
> fix docs onColumnMode -> oneColumnMode

- src/dd-gridstack.ts
- src/gridstack.ts
- src/types.ts
* moved _isNested & _styleSheetClass into gridstack instances instead as options (user will never specify)
> options cleanup

- demo/demo.css
- demo/float.html
- demo/index.html
- demo/nested_advanced.html
- demo/nested_constraint.html
- doc/CHANGES.md
- src/dd-draggable.ts
- src/dd-gridstack.ts
- src/dd-manager.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* partial fix for #1009
*  Create sub-grids on the fly, by dragging items completely over others (nest) vs partially (push) using new flag `GridStackOptions.subGrid.createDynamic=true`.
* ability to pause drag&drop collision until the user stops moving - see `DDDragOpt.pause`
TODO: need to make it work on already nested grids, remove nested on drag out, fix tests, more testing...
> using drag and drop to create nested Grids - part1

- demo/nested_advanced.html
- src/dd-droppable.ts
- src/dd-gridstack.ts
- src/gridstack.scss
- src/gridstack.ts
* more partial fix for #1009 and #992
* you can now drag a nested grid over another one and nest it deeper (992)
* fixed size transition
* fixed handlers not set when nesting
TODO: fix pause to work for enter/leave, more nested testing. Fix tests
> can drag nested grid over nested grid - Part 2

- demo/nested_advanced.html
- doc/CHANGES.md
- src/dd-droppable.ts
- src/dd-gridstack.ts
- src/dd-manager.ts
- src/gridstack-engine.ts
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
fix #1009 remaining issues
* dragging out last item will nuke empty nested grid
* dragging over item to create nested grid, will revert back to normal item if you continue to drag out
* fixed CSS issues dragging nested in/out couple times
TODO: fix test cases, doc, more testing
> using drag and drop to create nested Grids

- doc/CHANGES.md
- src/gridstack-engine.ts
* fix bug introduced when fixing #2043 (checking for 50% coverage before swap)
> fix #2055 maxRow=1 resize outside

- demo/serialization.html
- doc/CHANGES.md
- src/dd-draggable.ts
* fix for #2054
* make sure to prevent mousedown handling over known list of tags (like jqueryui did)
> Can't enter text in textarea

- demo/nested_advanced.html
- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/dd-gridstack.ts
- src/gridstack-engine.ts
- src/gridstack.ts
- src/utils.ts
more for #1009
* fixed makeSubGrid() to migrate node content field as well (not just html dom)
* save() now removes w,h of 1
* fixed dragging sub-grid over another, dragging content out not deleting empty sub-grid
* fixed test cases
> more nested grid fixes

- src/dd-touch.ts
Added a check if window exist
If it does not exist then most likely it is in SSR and should return isTouch = false
- [ yes ] All tests passing (`yarn test`)
> fix: document not defined error during SSR fixes #2073

- demo/serialization.html
- doc/CHANGES.md
- src/dd-touch.ts
- src/gridstack.ts
* make sure removeWidget() handles when item has been first removed from DOM (like Angular/React/Vue would do). This bug had been there for 3 years, but shown it's ugly head in  v6.
> fix removeWidget() after it's gone from DOM

- doc/CHANGES.md
- package.json
- spec/e2e/html/1985_read_1_column_wrong_12.html
- src/gridstack-engine.ts
- src/gridstack.ts
- src/utils.ts
fix #1985
fix #1975 (oneColumnModeDomSort case)
* we now handle DOM and addWidget() when temporally into 1 column mode better to save the full 12 column mode
* also DOM reading will reverse-sort entries to lay them in 1 column mode correctly (like if you had started with 12 and scaled down)
> 1 column mode loading, saving 12 column layout

- src/dd-draggable.ts
> bug #2063: editable elements focus and blur correction

- demo/float.html
- spec/gridstack-spec.ts
* updated float=true example with makeWidget() which works as expected
was used to reproduce these, but doesn't show issue...  #2114 #2115
> makeWidget() example

- README.md
- demo/angular-ngFor.ts
- doc/README.md
- src/types.ts
removed this comment since code uses different heuristics now
alwaysShowResizeHandle: 'mobile' // which defaults to /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
> mobile doc cleanup

- README.md
- demo/angular/README.md
- demo/angular/src/app/README.md
- demo/angular/src/app/app.component.html
- demo/angular/src/app/app.component.ts
- demo/angular/src/app/app.module.ts
- demo/angular/src/app/gridstack-item.component.ts
- demo/angular/src/app/gridstack.component.ts
- demo/angular/src/app/ngFor.ts
- demo/angular/src/app/ngFor_cmd.ts
- demo/angular/src/app/simple.ts
better #1824
* we now have a much cleaner and optimized Ng wrapper, as well as documented README file
* this needs fixes in the lib (upcoming release) to work correctly
> Complete Angular wrapper

- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* we now support calling addWidget() when there is an existing HTML element not yet initialized, but with creation options
* load() also now supports the same
* make sure grid and items have the correct GS styles (don't assume callee does when they init()/addWidget()
these are required by new Angular wrapper to optimizes updates. #2130
> addWidget() & load() fix for existing element

- demo/index.html
- demo/vue3js.html
- demo/vue3js_v-for.html
- doc/CHANGES.md
* fixed the given demo which was freezing making widgets and not removing items. PROBLEM:
let grid = ref(null);
grid.value = GridStack.init()
was causing proxy so all items were cloned and code compares node = node instead of ids...
> Vuejs error making GS freeze

- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
- src/types.ts
* fix #1842
* remove this never implemented feature out (per item resize handle support)
> removed incorrect doc/code on individual item resizeHandles

- demo/events.js
- src/dd-draggable.ts
- src/gridstack.scss
#2033
* since we don't animate resizing anymore (updated code comment and showing event demo) we don't really need to delay calling 'resizestop'
closing.
> resizestop example showing correct px values

- demo/events.js
- doc/CHANGES.md
- src/gridstack.ts
* bug from review #2162
removing item from a grid (into another) will now call `change` if anything was also modified during the remove
> removing item from a grid (into another) will now call `change`

- demo/two.html
- doc/CHANGES.md
- src/gridstack.ts
* fix #2110
* custom `GridStackOptions.itemClass` now works when dragging from outside
* updated two.html to showcase issue
> custom itemClass fix

- demo/react-hooks-controlled-multiple.html
- Adds change handler to set new layout  when items have been resized or moved
- Adds buttons for adding new item dynamically, for extending the example
- Mentions one possible bug in GridStack related to layout changing when an item has been removed from a grid
- Adds usage of ref instead of an id property
> improves new react demo example

- demo/react-hooks-controlled-multiple.html
* have fixed lib to call 'change' upon dropping item out if relayout happens, so workaround is lo longer needed
* make sure we update our internal structure (suing 'removed change' so get save() layout)
* updated comments
> more react demo example fixes

- ISSUE_TEMPLATE.md
- demo/nested_advanced.html
- doc/CHANGES.md
- src/gridstack.ts
* fix #2171
* we no longer store ops.subGrid for each nested grid. instead we parse the top grid that has this info and re-use it during create
* save() now handles saving only layout of subGrid more efficiently (don't list options)
* updated demo to showcase the issues
> nested grid save() incorrectly re-list children

- demo/angular/src/app/gridstack-item.component.ts
- demo/angular/src/app/gridstack.component.ts
- doc/CHANGES.md
- package.json
- src/dd-base-impl.ts
- src/dd-draggable.ts
- src/dd-droppable.ts
- src/dd-element.ts
- src/dd-gridstack.ts
- src/dd-manager.ts
- src/dd-resizable-handle.ts
- src/dd-resizable.ts
- src/dd-touch.ts
- src/gridstack-engine.ts
- src/gridstack-poly.js
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* while fixing #2110 I broke nested grid styles when manually dragging to sub-nest.
> regression fix: nested grids style issue

- src/gridstack.ts
- src/types.ts
Right now the scroll is way too fast. To prevent that I've implemented my own system of scrolling, but I need the possibility for the scroll to be disabled to make it work correctly 😅
> feat(scroll): add possibility to disable auto scrolling

- doc/README.md
- src/gridstack.ts
- src/types.ts
> fix(scroll): move the option to disable autoscroll

- demo/angular/src/app/README.md
- demo/angular/src/app/app.component.html
- demo/angular/src/app/gridstack.component.ts
* fixed event output to not re-use native
> angular demo update

- doc/CHANGES.md
- spec/e2e/html/2206_load_collision.html
- spec/gridstack-spec.ts
- src/gridstack-engine.ts
* make sure load() behaves the same as update() when dealing with collision. the issue was in batch mode we may no do collision in reverse order (to push items at the end first).
* added unit test for it, and html test
> `load()` with collision fix

- doc/CHANGES.md
- src/dd-draggable.ts
* had incorrectly commented out code that only allowed dragging by the specified handle in #2063
> restored grid option.handle check

- demo/vue3js_v-for.html
Vue will reset items in order if no 'key' property is set. So, the element and id won't be matched between vue and GridStack.
So, the solution is to add key property.
> Resolved: Grid engine.nodes count is incorrect after removing item.

- doc/README.md
- src/gridstack.ts
- src/types.ts
- src/utils.ts
I need to be able to pass a `nonce` to the `<style>` element created by GridStack, so I added a `nonce` property to `GridStackOptions`.
> feat: support nonce for CSP

- README.md
Let users join slack from the link provided in the Readme
the link of the invite is already in the template when we create an issue, but users that have failed a first time to connect to slack won't always think that the invite link works
Most dev communities are on discord now, most ppl are not used to slack anymore. At least I'm not 🤷‍♂️
> docs: slack invite link on Readme

- doc/CHANGES.md
- spec/e2e/html/2232_dom_auto_placement_mix.html
- src/gridstack-engine.ts
- src/gridstack.ts
fix #2232
* reading from DOM will  now place missing x,y items first available spot again (broke recently)
* added support to save original info including autoPlacement so if you laod into 1 column then go back to 12 it's the same as loading into 12 directly.
* added sample showing issue.
NOTE: need to verify why test fail now (might be correct behavior now).
> fix autoPlacement from DOM reading

- spec/gridstack-spec.ts
* fix #2232 test cases update for first issues (now correct) but second parts doesn't seem right... need to spend time  debugging this later
> test partial fix

- demo/angular/src/app/app.component.css
- demo/angular/src/app/app.component.html
- demo/angular/src/app/app.component.ts
- demo/angular/src/app/gridstack-item.component.ts
- demo/angular/src/app/gridstack.component.ts
- demo/angular/src/styles.css
- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* updated the Angular demo and wrapper to support nested grids
* fixed gridstack to call addRemoveCB for grids now, as well as sub-grid items
* WARNING: AddRemoveFcn had to change slightly to support calling grid or gridItem from same callback.
> feature: Angular nested grid

- README.md
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/810-many-columns.css
- spec/gridstack-spec.ts
- src/gridstack-engine.ts
- src/gridstack-extra.scss
- src/gridstack.scss
- src/gridstack.ts
- src/utils.ts
* fix #2243
* removed `gs-min|max_w|h` attribute  generated in CSS or written out as they are never used for rendering, only for initial load. This reduce our column/row styles in half!
> removed `gs-min|max_w|h` attribute

- demo/events.js
- doc/CHANGES.md
- spec/e2e/html/810-many-columns.html
- spec/gridstack-spec.ts
- src/gridstack.scss
- src/gridstack.ts
- src/utils.ts
* more fix #2243
* also removed `gs-w='1'` and `gs-h='1'` dom attribute writing since we already have min-width/min-height set, no need to set more attributes than needed. this will make girds with 1x1 items more compact/faster.
> removed `gs-w='1'` since min-width handles it

- doc/CHANGES.md
- spec/e2e/html/810-many-columns.html
- src/dd-draggable.ts
- src/dd-resizable.ts
* more fix #2243
* remove `'ui-draggable'` and `'ui-resizable'` since wasn't used in CSS and we have the `-disabled` version when off (so we can use `not(xyz-disabled)`).
> remove 'ui-draggable' 'ui-resizable'

- demo/angular/src/app/app.component.ts
- demo/angular/src/app/gridstack.component.ts
- demo/nested.html
- demo/nested_advanced.html
- demo/nested_constraint.html
- demo/old_nested-jq.html
- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* `GridStackOptions.subGrid` -> `GridStackOptions.subGridOpts`.
* We now have `GridStackWidget.subGridOpts` vs `GridStackNode.subGrid` (subclass) rather than try to merge the two at runtime since very different types...
always bugged me to have different runtime types, as it's error prone...
> Break: GridStackWidget.subGridOpts rename

- doc/CHANGES.md
- src/dd-draggable.ts
- src/gridstack.ts
- src/utils.ts
* fix #2275
* `setupDragIn()` now can take an array or elements (in addition to selector string) and optional parent root (for shadow DOM support)
> setupDragIn() shadow DOM support

- demo/index.html
- doc/CHANGES.md
- src/utils.ts
* fix #2234
* `Utils.getElements('1')` (called by removeWidget() and others) now checks for digit 'selector' (becomes an id)
> Utils.getElements('1') support

- doc/CHANGES.md
- src/gridstack.ts
> `destroy()` now removes event handlers too

- demo/two.html
help debug #2231
* will need to figure out why clone element is not used directly on drop later.
>  set an id through setupDragIn

- README.md
Updated SASS code to not used deprecated methods.
> Update README.md (SASS deprecation)

- README.md
- demo/demo.css
- doc/CHANGES.md
- src/gridstack-extra.scss
- src/gridstack.scss
- src/gridstack.ts
* break: remove `GridStackOptions.minWidth` obsolete since 5.1, use `oneColumnSize` instead
* optimize: CSS files now even 25% smaller (after being halfed in 8.0.0) by removing `.grid-stack` prefix for anything already gs based, and 3 digit rounding.
* grid-stack-12 now inserted (default column) since CSS is more specific now.
> CSS files now 25% smaller

- demo/demo.css
- doc/CHANGES.md
- src/gridstack.scss
so we don't break existing side panel grid item...
> restore some CSS specificity

- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
- src/utils.ts
* set root: HTMLElement | Document so either can be passed now
* more fix #2275
> setupDragIn() signature fix

- demo/serialization.html
- doc/CHANGES.md
- doc/README.md
- src/dd-draggable.ts
- src/types.ts
* you can now specify children that will prevent item from being dragged when clicked on.
* fix for #2205
* updated demo to showcase custom non draggable item
> GridStackOptions.draggable.cancel option

- README.md
- doc/CHANGES.md
- karma.conf.js
- spec/e2e/html/810-many-columns.css
- spec/gridstack-spec.ts
- src/gridstack-extra.scss
- src/gridstack.scss
- src/gridstack.ts
* fix #2314
* issue with having min-height/width instead of height/width for gs-h|x="1"
* further compressed CSS multi column rules (use `.gs-# > .grid-stack-item` instead of `.grid-stack-# > .grid-stack-item`)
> fix gs-h|x="1"

- angular/projects/demo/src/app/app.component.ts
- angular/projects/demo/src/app/app.module.ts
- angular/projects/demo/src/app/dummy.component.ts
- angular/projects/lib/src/lib/base-widgets.ts
- angular/projects/lib/src/lib/gridstack-item.component.ts
- angular/projects/lib/src/lib/gridstack.component.ts
- angular/projects/lib/src/public-api.ts
- doc/CHANGES.md
* fixed to make sure dynamic  components are destroyed
* added support for saving/loading custom data per widget
> angular wrapper - serialize custom data support

- doc/CHANGES.md
- src/gridstack.ts
* addRemoveCB may have the user call makeWidget() so prevent multiple instances (which oddly created clone nodes) from happening.
* also makeWidget() (now call form addWidget()) checks for nested grid options. same optimization remains.
> addWidget() addRemoveCB checks if already initialize widget

- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* `GridStackWidget.id` is now string only (used to be numberOrString) as it causes usage to have to check and cast
> `GridStackWidget.id` is now string only

- doc/CHANGES.md
- src/gridstack.ts
* fix #2349
* we now support grid disableDrag vs Item noMove (lowest wins if set)
> grid NoMove vs item NoMove support

- doc/CHANGES.md
- spec/e2e/html/2357_rem.html
- src/gridstack.ts
* fix #2357 and added demo for it
> NaN inf loop when using cellHeight rem/em

- doc/CHANGES.md
- src/dd-draggable.ts
- src/gridstack.ts
- src/utils.ts
* fix #2354
* external items (like toolbar) might have grid-item attr we want to clone, so don't clear them
> don't clear (default) attr when dragging outside item in

- demo/column.html
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/types.ts
- src/utils.ts
* fix #2358 when your grid is display a sorted list of items, we now support reflowing that content during column resize and compact() methods.
* compact() now takes options which today can be CompactOptions = 'list' | 'compact';
* column(N) now has new options ColumnOptions = 'list' | 'compact' | 'moveScale', etc...
* also optimized some code while stepping in debugger.
API is backward compatible and defaults  to the same behavior.
TODO: remember bigger width and restore back when going up in columns...
> (feat) column() resizing now supports 'list' | 'compact' modes

- demo/column.html
- doc/README.md
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
* more fix #2358
* going 12 -> 1 -> 12 in 'list' mode now correctly restore original item width before doing compact()
* updated demo
* updated API docs
> column(n, 'list') handles restore back to 12 size

- src/gridstack.ts
- src/types.ts
An attribute 'decline' has been added to 'removableOptions' to deny the removal of a specific class. By default, it is set to 'grid-stack-non-removable'."
> add a class that defines a non removable grid item

- doc/CHANGES.md
- doc/README.md
- src/dd-droppable.ts
- src/gridstack.ts
- src/types.ts
> decline feat cleanup

- demo/index.html
- demo/vue3js_dynamic-render_grid-item-content.html
- demo/vue3js_dynamic-render_grid-item.html
Adds two new demos, as a starting point for Gridstack driven Vue rendering. These demos could be used as a reference point for creating Vue/GridStack components.
* `demo/vue3js_dynamic-render_grid-item.html`
Shows vue rendering the entire grid item element called in GridStack.addRemoveCB
* `demo/vue3js_dynamic-render_grid-item-content.html`
Shows vue rendering only the grid content in grid events.
These demos have not been tested with nested grids or multi-grid setups.
> Demos for Vue3 Dynamic Rendering using Gridstack

- angular/projects/demo/src/app/app.component.html
- angular/projects/demo/src/app/app.component.ts
- angular/projects/demo/src/styles.css
added two grid demo to angular demo. showing issue with component not being created/deleted when dragged.
> ng two.html demo

- angular/projects/demo/src/environments/environment.prod.ts
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* dragging onto trash now calls removeWidget() and therefore `GridStack.addRemoveCB` (for component cleanup)
> drag to trash calls removeWidget()

- spec/e2e/html/2357_rem.html
- spec/e2e/html/2384_update_content.html
- src/gridstack.ts
* fix #2384
* you can now update the widget content while having a nested grid
* added an example showing the issue
> Nested grid support with content update

- doc/CHANGES.md
- src/gridstack.ts
- src/utils.ts
* you can now re-order widgets during load() using autoPosition:true
> `load()` support re-order loading with autoPosition

- demo/fitToContent.html
- demo/index.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* fix #404
* added `GridStackOptions.fitToContent` and `GridStackWidget.fitToContent` to make gridItems size themselves to their content (no scroll bar), calling `GridStack.resizeToContent(el)` whenever the grid or item is resized
* added demo showing behavior
* fixed sizing event to use much more accurate ResizeObserver on grid rather than generic window.addEventListener('resize')
> auto-size height to fit content

- doc/CHANGES.md
- spec/e2e/html/2406_inf_loop_autoPosition_column1.html
- src/gridstack-engine.ts
- src/gridstack.ts
* this was a very particular flow where autoPosition were loading into 1 column (so we save the higher grid count layout) then switch to 2 column, then loaded new items.
* also fixed new v9 issue with sizing called with column 1 already.
> #2406 inf loop fix adding autoPosition in 1->2 column

- README.md
- demo/fitToContent.html
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
more fix #404
* changing column size and manually resizing a widget will now call resizeToContent()
* added resizeToContentCB for app to override how to resize.
* Added `resizeToContentParent` to make generic code more robust.
* fixed some 1 column loading Nan issues
> fitToContent fixes

- src/dd-touch.ts
If device has touchscreen, gridstack emulates mouse event from touch event + calls handler for pointer event. If user uses mouse, we don't need to manipulate with pointer event. So I check pointerType inside pointer events handlers.
https://github.com/gridstack/gridstack.js/issues/2413
> fix(drag): fix mouse drag on devices with touchscreen

- doc/CHANGES.md
- src/dd-touch.ts
> touchscreen tweaks

- demo/fitToContent.html
- doc/CHANGES.md
- src/gridstack.ts
* partial fix for #2427
* when changing cellHeight, or calling addWidget() | makeWidget() we now call doContentResize()
* fixed doContentResize logic to use expected size (using cellHeight) instead of actual DOM values so we don't need to delay until animation is done (unlike column width which does affect calc height for content reflow)
TODO: support 1rem type of cellHeight.
> fitToContent when calling cellHeight()/addWidget/MakeWidget

- demo/sizeToContent.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* `sizeToContent` now supports being `boolean|number` to limit the height but user can resize past that, unlike maxH.
* more #404 fixes
> sizeToContent number support

- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* more fix #404
* resizeToContentParent is now GridStackWidget var as well (local override) for widgets that needs to resize differently.
> more resizeToContent fixes

- src/gridstack-engine.ts
* fix #2435 moved overMax outside of loop.
> directionCollideCoverage() tweaks

- doc/CHANGES.md
- src/gridstack.scss
- src/gridstack.ts
* fix resizeToContent() to handle node.h (using when cellHeight changes or we resize) vs DOM sizing (rest of the time) more #404
> tweaks to resizeToContent()

- doc/CHANGES.md
- src/gridstack-engine.ts
* fix #2449
* move, while still being under maxRow or at least not making it worse (case where widget was somehow added past our max)
> full grid maxRow fix

- demo/nested.html
- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* nested grids now support `sizeToContent` to size themselves to how many sub items they contain - Thank you [@Helix](https://gridstackjs.slack.com/team/U05QT7G8H7T) for sponsoring this!
> nested grids now support `sizeToContent`

- src/gridstack.ts
- src/types.ts
tweak to resizeToContentCB - now takes useAttr
> tweak to resizeToContentCB - now takes useAttr

- demo/nested_advanced.html
- src/gridstack.ts
- webpack.config.js
rather than min-height again (apart for nested grids which need it) and partial getComputedStyle CSS minHeight support
- [x Created tests which fail without the change (if possible)
> fix _updateContainerHeight() to use height

- doc/CHANGES.md
- src/gridstack.ts
- src/utils.ts
sub-grid styles now look for immediate correct parent, not any depth above.
> sub-grid styles fix

- doc/CHANGES.md
- spec/e2e/html/2469_min-height.html
- src/utils.ts
* fix #2469 "Invalid height" error CSS minHeight
> "Invalid height" error CSS minHeight

- src/gridstack-engine.ts
- src/gridstack.ts
Fix #2394 by removing dropped nodes from GridstackEngine's layout cache. 
I checked `1985_read_1_column_wrong_12.html` (the code relevant here has been added in that PR) and the behaviour is the same as before. Nodes are still positioned correctly after initialising in one column mode, and then enlarging the window (no matter how they are added)
> Remove added node from layout cache on drop event

- doc/CHANGES.md
- spec/e2e/html/2394_save_sub_item_moved.html
- src/gridstack-engine.ts
- src/gridstack.ts
* fix #2394]
* better fix that makes sure we keep wanted size when an item is dropped on us (so we remember in case we change grid column)
* also changed to not save x,y during dropping since the drag behavior will figure where to put it, and that means we don't cache that layout that might not apply to the new grid anyway.
* added a running example showing issue.
> better fix: nested grid size issue

- demo/index.html
- demo/scale.html
- demo/web2.html
- src/dd-draggable.ts
- src/dd-resizable.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
The position of elements dragged was badly calculated and resulted in weird behaviour in a lot of cases like:
- Disable automatic scroll, scroll page while dragging 
- Zoom out/in using the `scale` css property and try to drag a component
https://github.com/gridstack/gridstack.js/issues/1275
> fix(drag): always put element under the mouse when dragging an element

- demo/esmodule.html
- demo/index.html
> took ES module demo out

- doc/CHANGES.md
- spec/e2e/html/2492_load_twice.html
- src/gridstack-engine.ts
- src/gridstack.ts
- src/utils.ts
* fix #2492
* make sure we use existing items and not reset to start from scratch so we do collision at each step.
> calling load() allows overlapping widgets

- demo/sizeToContent.html
- src/gridstack.ts
* more fix #2492
* load() now calls doContentResize() at the end.
* also fixed update() same content bug returning pre-maturely.
> doContentResize called in load()

- src/gridstack-engine.ts
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* more fix #2492
* back to clearing the list when doing load() to make sure we insert like if it was new, but make sure we force a collision check
> more load() fixes

- demo/transform.html
- src/dd-draggable.ts
- src/dd-resizable.ts
When wanting to drag a grid item within a parent that is scaled using CSS transforms it doesn't work properly.
This PR serves as a solution for issue #1275 by determining the scaling factor applied to the parent to adjust the grid position and size. e.g. if the parent is scaled with scale(0.5), the scaling factor will be 2.
Additionally, here is a video demonstrating how this fix works in action.
https://github.com/gridstack/gridstack.js/assets/90270530/9e9677fc-008e-4b62-aa32-c123fc76b80d
> fix(scale): update drag & resize when the gridstack parent is scaled

- demo/events.js
- doc/CHANGES.md
- src/gridstack.ts
* better fix #2489
* removed the timeout in the  dropped event handler and call dropped event last
* tested two.hml and seems to work - can't recall wy we set event handler on a timeout (might have been pre mouse handler code)
> removed dropped event setTimeout()

- doc/CHANGES.md
- src/utils.ts
* fix #2497
* make sure to check for height=''
> parseHeight() fix

- doc/CHANGES.md
- src/gridstack.ts
- src/utils.ts
* regression where setting column(1) manually would revert back on next window resize.
> fix column(1) to not restore if disableOneColumnMode

- src/dd-draggable.ts
Fixed unhandled exception happening in _mouseMove handler on line 209, 'this.el' is undefined. Happens if element is removed just before call of _mouseMove and just after _mouseDown.
I am unable to run yarn test. Gets all kinds of strange errors.
I had a setup easily reproducing the issue. After the fix, I could not reproduce it anymore.
> Fixed unhandled exception happening in _mouseMove handler

- doc/CHANGES.md
- src/gridstack.ts
* fix potential crash in doContentResize() if grid gets deleted by the time the delay happens
> fix potential crash in doContentResize()

- src/gridstack-engine.ts
add more strict interface for `GridStackEngine` class. It allows to extend engine (or make custom one) in projects with strict tsconfig
> fix(typings): make engine interface strict

- demo/serialization.html
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* fix #2527
* turned out to be much more complicated fix than expected. cleanup some of the code while debugging through it...
* make sure we nodeBoundFix() before widthChanged is checked
* cacheLayout() now checks fo existing node id so loading again doesn't mess things up
> Incorrect layout on grid load in one column mode

- README.md
- angular/projects/demo/src/app/app.component.ts
- demo/canvasJS.html
- demo/column.html
- demo/custom-engine.html
- demo/drag-and-drop-dataTransfer.html
- demo/index.html
- demo/mobile.html
- demo/nested.html
- demo/old_two-jq.html
- demo/react-hooks-controlled-multiple.html
- demo/responsive_break.html
- demo/two.html
- demo/web1.html
- demo/web2.html
- doc/CHANGES.md
- doc/README.md
- spec/e2e/html/1570_drag_bottom_max_row.html
- spec/e2e/html/1571_drop_onto_full.html
- spec/e2e/html/1858_full_grid_overlap.html
- spec/e2e/html/2394_save_sub_item_moved.html
- spec/e2e/html/2469_min-height.html
- spec/e2e/html/2492_load_twice.html
- spec/gridstack-spec.ts
- src/gridstack.ts
- src/types.ts
* we now support much richer responsive behavior with `GridStackOptions.responsive` including any breakpoint width:column pairs, or automatic column sizing
* `disableOneColumnMode`, `oneColumnSize`, `oneColumnModeDomSort` have been removed (see v10 migration doc)
* added new demo files.
* TODO: update test files, more testing...
> new `GridStackOptions.responsive`

- src/gridstack.ts
make sure 'new GridStack(el)' set el.gridstack=this right away as code during loading might depend on those vars being set.
> make sure 'new GridStack(el)' set el.gridstack=this

- doc/README.md
Method `addSubGrid` does not exist
> chore: replace addSubGrid with makeSubGrid

- src/gridstack.ts
- src/utils.ts
This is a fix for web components that use the shadow dom.
Basically, whenever a stylesheet is removed, `document.querySelector()` is used, and this doesn't work when gridstack is used within a shadow root. 
To fix this, we can make use of the `styleLocation`, which describes whether we're attaching the styles in a parent node or the head of a document
> fix: remove style node when attached to parent node in a shadow root

- demo/sizeToContent.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
- src/types.ts
* fix #2552 where dom init wasn't calling sizeToContent
Also:
* fixed drag&drop not calling size either
* prevent animation when loading (from empty) and when replacing placeholder with actual content (helps in sizeToContent)
* resizeToContent() no longer use dic sizing (only node.h) so we rarely have to delay for animation (only when column widget changes)
* bunch of renames (internal) to make cleaner.
*** POSSIBLE BREAK (unlikely)
* ResizeToContentFcn doesn't take optional useAttr arg anymore
> sizeToContent fixes (animation, DOM init, cleanup)

- doc/CHANGES.md
- src/gridstack.ts
* tweak to #2561
* drap&drop not having added element)
> more sizeToContent fixes

- demo/sizeToContent.html
- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
* fix #2427
* getCellHeight() now support rem/em natively (before items are sized correctly)
> rem/em support for sizeToContent

- doc/README.md
- spec/utils-spec.ts
- src/gridstack.ts
- src/utils.ts
Allow `cm` and `mm` units for cell height. I am using this to create a printable layout that's consistent across devices when printing on paper. The only way to achieve that is by using `cm` and `mm` units. This small PR allows the two additional CSS units.
> Allow cell height in cm and mm units

- doc/CHANGES.md
- spec/e2e/html/2576_insert_column_shift_content.html
- src/gridstack-engine.ts
- src/gridstack.ts
* fix #2578 column('none') now ignores layouts
> column('none') now ignores layouts

- src/gridstack.scss
Improves scaling in browser. Proposed in https://github.com/gridstack/gridstack.js/pull/2550#issuecomment-1875794188. Fixes minor regression in #2550.
Before #2550:
After #2550 and before this change:
After this change:
- [n/a] Created tests which fail without the change (if possible)
- [n/a] All tests passing (`yarn test`)
- [n/a] Extended the README / documentation, if necessary
> Set dimensions on resize arrow SVG

- src/gridstack.scss
Update SVG to take `2px` padding into consideration (20x20 container for a 16x16 SVG).
> 🍱 fix blurry resize arrow

- src/gridstack.ts
Add type overloading to the `on` and `off` function to obtain better type hints in development. An example is shown in the following figure:
> add `on` function overloading for better type hints

- src/dd-droppable.ts
- src/gridstack.ts
If you quickly drag elements between nested blocks, duplicates of the same element appear.
> Fix quickly drag elements between nested blocks

- doc/CHANGES.md
- src/dd-droppable.ts
> nested grid fix #2560

- demo/nested.html
show how to add a subgrid with widgets inside either programmatically or by drag and drop. what do you think?
> demo: nested drop

- src/gridstack.ts
- src/utils.ts
Fixed the problem where document doesn't exist on server side
> fix(ssr): problem with document not existing on server side

- src/dd-draggable.ts
- src/dd-resizable.ts
- src/gridstack.ts
- src/utils.ts
This fixes the issue i mentioned in https://github.com/gridstack/gridstack.js/issues/2575
Some of the code was added from https://github.com/gridstack/gridstack.js/commit/3c9bc4b1dc394201900c147f185c29ca5c892603 to the event handler for dragging when acceptWidgets is set to true (which is located in gridstack.ts and not in dd-draggable.ts)
> apply position scaling when acceptwidgets is enabled

- doc/CHANGES.md
- src/dd-draggable.ts
- src/dd-resizable-handle.ts
* our app was showing errors calling e.preventDefault() because move events were marked as passive (which are more performant for smooth scrolling) so explicitly  set it passive and skip the call.
* verified the old issue of sweep selecting text field content isn't an issue anymore
> using passive:true for mousemove events

- src/dd-gridstack.ts
- src/dd-resizable.ts
* since sizeToContent:true will automatically size the content vertically, don't let the user change the height to start with
Note: tried to change the feedback to have e,w arrows but we only have 10px area which is too narrow to show feedback (we have 20x20 for corners that may overlap content which is ok). Showing normal handles for now.
> restrict vertical resize with sizeToContent

- src/gridstack.ts
If you call addWidget inside the grid added or removed events, the items passed in the event for the 
Calling **addWidget** inside the **"added"** event triggers another **"added"** event with the **items** argument containing the newly added item and the initial item that triggered the first **added** event. The second **"added"** event should contain only the newly added item.
This happens because the **"added"** event is triggerd first and the internal **addedNodes** array is emptied afterwards. The fix was to empty the **addedNodes** array before triggering the **"added"** event.
The same happens when calling **removeWidget** inside the **"removed"** event.
> empty addedNodes and removedNodes before triggering event to prevent infinite loop

- doc/CHANGES.md
- src/dd-gridstack.ts
- src/dd-resizable.ts
- src/utils.ts
fix #2612 to allow resize when you have a number (soft max)
> resize with sizeToContent

- angular/projects/demo/src/app/app.component.ts
- angular/projects/demo/src/app/dummy.component.ts
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* make sure we call CB like when removing single items
> removeAll() trigger Angular's ngOnDestroy

- src/gridstack-engine.ts
> fix/2503: break on locked node collision

- src/utils.ts
Fixes #2584
From my manual testing everything looks fine.
> fix/2584: refactored sort function

- doc/CHANGES.md
- doc/README.md
- src/gridstack-engine.ts
- src/gridstack.ts
- src/utils.ts
* fix #2630 to handle undefined x,y values again
POSSIBLE BREAKING CHANGE
* Utils.sort() and GridStackEngine.sortNodes() no longer take column as not needed actually...
> sort() no longer takes column

- doc/CHANGES.md
- spec/e2e/html/2639_load_missing_coord.html
- src/gridstack.ts
* fix #2639
* make sure we separate out new item that don't have coordinates to be added afterward
> load() fix with mix of new item without coordinates

- doc/CHANGES.md
- spec/e2e/html/2633_drop_full_crash.html
- src/gridstack.ts
* fix #263
* prevent dropping into a full grid (code was already there but failed to create node for testing from outside)
> Drop into full grid fix

- README.md
- angular/projects/demo/src/app/app.component.ts
* fix #2559
* changed demo to not insert new item at specific location, but appendZ
* ng demo now supports 1 column mode again
> angular demo tweaks

- doc/CHANGES.md
- spec/e2e/html/2453 _recreated_trash.html
- src/gridstack.ts
* fix #2453
* make sure _setupRemoveDrop() is static since it is a shared and not per grid
* also bit more optimization during destroy()
> recreated grid trash issue

- demo/responsive.html
- doc/CHANGES.md
- src/gridstack.ts
> handle minW resizing when column count is less

- doc/CHANGES.md
- spec/e2e/html/2677_drag_button.html
- src/dd-draggable.ts
* fix #2677
* allow event target to be draggable even if in the blocked list if that is the specified handle.
> allow button as handle dragging

- demo/two.html
- doc/CHANGES.md
- doc/README.md
- src/dd-draggable.ts
- src/dd-resizable-handle.ts
- src/gridstack.ts
* You can now press 'Esc' to cancel a move|resize
* 'r' to rotate during a drag
* added `GridStack.rotate()` as well Thank you John B. for this feature sponsor
> 'Esc' to cancel drag/resize, 'r' to rotate drag

- doc/CHANGES.md
- src/gridstack.ts
* fix for #2683 
untested as I don't have my dev machine right now.
> check for fixed grid maxRow during resize

- doc/CHANGES.md
- src/gridstack.ts
* fix #2694
* not tested as I don't have my dev machine right now
> prevent 'r' rotation to items that can't resize

- src/dd-draggable.ts
- src/gridstack.ts
- src/utils.ts
> prevent 'r' rotation to items that can't resize (2)

- src/dd-draggable.ts
I added an extra nullcheck before performing the key event callback. If `n` or `n.grid` aren't defined then just `return`.
> Bugfix: prevent throwing error when node.grid is undefined (drag item from outside the grid)

- doc/README.md
- src/dd-gridstack.ts
* fix #2708
removed old `dragOut` from doc since it is no longer supported (jquery UI feaure)
> removed old `dragOut` from doc

- src/dd-draggable.ts
Currently when options handle is defined it applies event listeners to the first instance that has the handle class. These changes add the events to all elements that has the handle class allowing for multiple drag handles with in a grid item
> support for multiple drag handles

- doc/CHANGES.md
- src/dd-draggable.ts
* more for #2709
* correctly removed prev dragEl code and use list
> support for multiple drag targets fix

- doc/CHANGES.md
- src/gridstack.ts
* fix #2669 
* make sure we clear the _orig field as bash mode off retore for flaoting case
> load() sometimes restore incorrectly

- src/gridstack.ts
* more fix #2669
* load() force 1x1 default
> load() force 1x1 default

- demo/two.html
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* changed code to create widgets in sorted order instead of reverse order (fixed collision code to handle that case to push down items during collision)
* updated two.html to force collision loading to test
> load() now creates in order

- doc/CHANGES.md
- src/gridstack.ts
- src/utils.ts
* fix  #2734
* this was introduced by another fix in 10.2.1
> fix rotation error

- doc/CHANGES.md
- src/gridstack.ts
resizeToContent JS error with nested grid
> resizeToContent JS error with nested grid

- doc/CHANGES.md
- src/dd-draggable.ts
* fix #2740
* make sure we don't look for all draggable items when we're a nested grid, only first (grid-content)
> nested grid drag fix

- doc/CHANGES.md
- src/dd-gridstack.ts
- src/dd-resizable.ts
- src/gridstack.ts
* fix #2730
* we now have a max remaining left side and top side so we can correctly resize elements that are places at the edge, sizing back towards (0,0)
> resizing left from right most item works

- demo/web-comp.html
- demo/web1.html
* fix #2756
* web1.html uses -all.js like the others
* force lit-element@3 as apparently current 4.1 isn't working for this (old ?) demo.
> demo fixes, web component

- README.md
- demo/column.html
- demo/knockout.html
- demo/right-to-left(rtl).html
- demo/serialization.html
- demo/sizeToContent.html
- demo/web1.html
- demo/web2.html
- demo/website.html
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* fix #2736
* All instances of `el.innerHTML = 'some content'` have been removed for security reason as it opens up some potential for accidental XSS
* addWidget(w: GridStackWidget) only signature
* fixed RTL demo
see readme V11 for more info
> GridStackWidget.content only used as textContent

- angular/projects/demo/src/app/app.component.html
- angular/projects/demo/src/app/dummy.component.ts
- angular/projects/lib/src/lib/gridstack-item.component.ts
- angular/projects/lib/src/lib/gridstack.component.ts
* possible fix #2753
* while I was never able to reproduce real angular leak (all size show as 'code' and not detatched nodes) I made some changes that might adress issues.
* devs will have to provide example showing issue at this point...
> ng memory leak

- angular/projects/demo/src/app/app.component.html
- angular/projects/demo/src/app/app.component.ts
- angular/projects/demo/src/app/dummy.component.ts
- angular/projects/demo/src/styles.css
* updated Angular to upcoming v11 demo.html to create components now for sidebar!
> angular V11 APi support

- angular/projects/demo/src/app/app.component.html
- angular/projects/demo/src/app/app.component.ts
- angular/projects/demo/src/app/app.module.ts
- angular/projects/demo/src/app/dummy.component.ts
- angular/projects/demo/src/styles.css
- angular/projects/lib/src/lib/base-widget.ts
- angular/projects/lib/src/lib/gridstack.component.ts
- doc/CHANGES.md
- src/dd-gridstack.ts
- src/gridstack.ts
* modified Ng exmaple to show a component that contains a sub-grid (in addition to being a sub-grid example)
* fixed GS code to support sub-grids that are not direct children on a grid-item-content but further down
Note: this will depend on upcoming V11
> angular support for nested Grid components

- demo/index.html
- demo/lazy_load.html
- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* you can now set grid | widget `lazyLoad:true` to only create content (more unseful in Angualr wrapper) until widget is scrolled into view.
> lazyLoad support to delay load widget content until visible

- angular/package.json
- angular/projects/lib/package.json
- angular/yarn.lock
- package.json
* looks like ng18 was adding a .npmignore to skip our (nested) package.json which is required to compile our demo.
will need to re-release v11.0.1 soon.
> fixed v11 angular missing package.json

- demo/two.html
- doc/CHANGES.md
- src/gridstack-engine.ts
* when a widget is created, make sure the user supplied id is unique, else we will have issues during load()/update()/etc...
> make sure we have unique USER id

- angular/README.md
- angular/projects/demo/src/app/app.component.html
- angular/projects/demo/src/app/ngFor.ts
- angular/projects/demo/src/app/ngFor_cmd.ts
* demos are using new syntax, readme has both
* left the wrapper angular 14-18+ compatible.
> using angular 17 demo syntax

- spec/gridstack-engine-spec.ts
- src/gridstack-engine.ts
Some applications can use default column number (for the largest resolutions) higher than 12. 
In that case, during column count dynamic switch due to responsive-based resizes, it can happen that the `nodeBoundFix` function would try to cap the coordinates to 12 rather than the default max column number.
With this fix it is then possible to subclass `GridStackEngine` and change the default "max" column, rather having the constants hard-coded in the codebase.
Thx, L.
> Default columns arg for non-12 columns scenarios

- angular/projects/demo/src/app/app.component.html
- doc/CHANGES.md
- react/lib/constants.ts
- spec/gridstack-engine-spec.ts
- spec/gridstack-spec.ts
- spec/test.html
- src/gridstack-engine.ts
- src/gridstack.ts
fixed the main test file which exposed multiple bugs! :
* GridStack:init(null) didn't set this.opts
* loading exiting layout incorrecly moved items (when just one caused collision)
* update(el, {id: 'newId'}) didn't update the id
* some attr setting optimization
going forward need to get full test coverage to help find issues...
continue #2850
> fix tests and newly found bug

- demo/nested.html
- doc/CHANGES.md
- spec/e2e/html/2576_insert_column_shift_content.html
- src/gridstack.ts
- src/types.ts
* fix #2864
* reiszing subgrid will now reflow content as requested. 'none' was changed to do nothing (so user can custimize/load/overide) a little while back.
> added `GridStackOptions.layout` for nested grid reflow

- spec/e2e/html/2864_nested_resize_reflow.html
- spec/regression-spec.ts
- src/gridstack.ts
* more fix #2864
* make sure API resizing also reflows the content, deal with animation for force re-layout right away before animating items away.
> more nested grid reflow

- src/gridstack.scss
- src/gridstack.ts
The NE & NW resize handles aren't positioned correctly when using custom `margin` grid option.
Here is an example [jsfiddle](https://jsfiddle.net/richsalcedo6/f1zhneca/).
This PR fixes the issue on my local testing
- I am unable to successfully run the tests on my macbook. It's having a karma error. I didn't have enough time to figure this out
> Fix positioning bug with NE,NW resize handles

- README.md
Typo on example
Fixed typo on example
GridStackNod -> GridStackNode
> Update README.md - GridStackNod to GridStackNode

- demo/demo.css
- demo/nested.html
- doc/CHANGES.md
- src/gridstack.ts
* make sure children default to parent values unless explicitly set.
* subgrid default include: column: 'auto', columnOpts: undefined, layout: 'list', subGridOpts: undefined
> sub-grid inherit parent opts by default

- demo/demo.css
- demo/nested.html
- doc/CHANGES.md
- src/gridstack.ts
* resizeToContent() now handle content above sub grid
* updated demo to showcase sub-grid with header content.
> resizeToContent() now handle content above sub grid

- angular/README.md
- angular/angular.json
- angular/package.json
- angular/projects/demo/.browserslistrc
- angular/projects/demo/src/app/app.component.html
- angular/projects/demo/src/app/app.component.ts
- angular/projects/demo/src/app/app.module.ts
- angular/projects/demo/src/app/ngFor.ts
- angular/projects/demo/src/app/ngFor_cmd.ts
- angular/projects/demo/src/main.ts
- angular/projects/demo/src/test.ts
- angular/projects/lib/src/lib/gridstack-item.component.ts
- angular/projects/lib/src/lib/gridstack.component.ts
- angular/projects/lib/src/test.ts
- angular/tsconfig.json
- angular/yarn.lock
- package.json
* downgraded the build back to ng14 so we can have maximun compatibility
* components are still standalone for more native ng19 standard, btu will compile with ng14 with and without a module.
> angular downgrade v19 - v14

- doc/CHANGES.md
- src/dd-draggable.ts
* fix #2887
* make sure we check for null since dragging a child out will destroy the old one, doing a double cleaning.
> mobile: nested grid drag out fix

- spec/gridstack-spec.ts
- src/gridstack.ts
- src/utils.ts
The current implementation of gridstack styling is based on a <style> node appended in the parent `div`. However this element doesn't contain any CSS text content: his `style` content is rather manipulated as a `CSSStyleSheet` object.
This works fine unless the parent `div` is detached from the document, and then reattached. This operation can be common if gridstack containers are hosted in some type of high-level container (like tabs) that supports reorder.
It seems that the issue is somewhat related to the fact the `CSSStyleSheet` instance depends on the parent DOM context. So, when detached, the style content is reset.
Using CSS as text rather than opaque style object fixes the issue.
Probably the best approach to leverage `CSSStyleSheet` objects is to switch to HTML Custom Elements …
> Support gridstack element node reparenting without losing the stylesheets

- demo/two.html
- doc/CHANGES.md
- src/gridstack.ts
* fix #2900
* use attr `data-gs-widget` instead of `gridstacknode` (supported as well for backward compatibility)
> use attr `data-gs-widget`

- demo/vue3js_dynamic-modern-renderCB.html
New demo of Vue3 render functions using GridStack.renderCB
Benefits 
- less code than using GridStack.addRemoveCB, since GridStack creates the 2 needed parent divs + classes
- more information passed to GridStack.renderCB() - (entire GridStackWidget is passed so you can use id or some other field as logic) 
- less templating needed (no need for div class="grid-stack-item wrapper) in each Vue component 
- fixes {{ info }} display
Checklist N/A
> New demo - Vue3 render functions with GridStack.renderCB

- doc/CHANGES.md
- src/dd-draggable.ts
- src/gridstack-engine.ts
- src/gridstack.ts
* fix 2695
* 'Esc' to cancel now works on sidebar external items
* also works dragging over trash
> 'Esc' to cancel now works on sidebar

- demo/css_attributes.html
- demo/demo.css
- demo/index.html
This PR adds a small demo HTML page showcasing how to use the `gs-*` attributes gridstack.js provides in CSS, in this case to display the widgets dimensions.
This is a follow-up of this comment: https://github.com/gridstack/gridstack.js/pull/2854#issuecomment-2479172427
> Add demo showcasing how to use gridstack.js attributes in CSS

- doc/CHANGES.md
- src/gridstack.ts
* added `isIgnoreChangeCB()` if changeCB should be ignored due to column change, sizeToContent, loading, etc...
> added `isIgnoreChangeCB()`

- src/dd-touch.ts
The deprecated method initMouseEvent has been replaced by the MouseEvent constructor. Additionally, compose: true has been added to allow gridstack.js to be used inside of a web component with touch events.
> Replaced initMouseEvent with MouseEvent constructor and added composed: true

- demo/index.html
- demo/responsive_none.html
- doc/CHANGES.md
- src/gridstack-engine.ts
- src/gridstack.ts
* added `responsive_none.html` demo and fixed layout:'none' to bound check the layout (no-op unless it must change)
> added `responsive_none.html`

- src/dd-touch.ts
- src/utils.ts
fix #2921 to remove the remaining 2 initMouseEvent() calls.
> more initMouseEvent replacement

- demo/demo.css
- demo/lazy_load.html
- demo/title_drag.html
- doc/CHANGES.md
- src/gridstack.ts
- src/utils.ts
* fix #2939
* MakeWidget() will not call drag&drop init if lazy load - which is done after content is renderCB instead.
* added `Utils.lazyLoad()` to make it easier to check.
> custom drag handle + lazyLoad fix

- angular/README.md
- demo/index.html
> better Ng doc

- angular/projects/lib/src/index.ts
- angular/projects/lib/src/lib/base-widget.ts
- angular/projects/lib/src/lib/gridstack.component.ts
- angular/projects/lib/src/lib/gridstack.module.ts
- angular/projects/lib/src/lib/types.ts
- doc/CHANGES.md
* fix #2955
* moves ng types into it's own plain file, fix order of include/export to reflect heirachy Note: gridComp depends on gridItem but not other way around
> fix /angular circular dependencies

- doc/CHANGES.md
- spec/e2e/html/2951_shadow_dom.html
- src/dd-draggable.ts
* fix #2951
* check for helper not having a parent before re-appending (rather than search though entire dom + shadow)
* added example test
> shadow DOM drag re-append fix

- doc/CHANGES.md
- src/gridstack.ts
- src/types.ts
- src/utils.ts
* internal `_prepareDragDropByNode(n)` is now public as `prepareDragDrop(el)` so Angular, React, and others can call once the DOM content elements have been added (the outside griditem divs are always created for content)
> new public prepareDragDrop(el)

- README.md
- demo/sizeToContent.html
- demo/two.html
- doc/CHANGES.md
- src/gridstack.ts
- src/utils.ts
* fix #2959
*  `Util.createWidgetDivs()` has moved to `GridStack.createWidgetDivs()` to remove circular dependencies
NOTE: possible breaking change for some.
> Util to GridStack.createWidgetDivs() move

- demo/sizeToContent.html
- demo/two.html
- src/gridstack.ts
* this.createWidgetDivs() since it needs this.opts.itemClass anyway, instead of static method.
* more fix #2959
> this.createWidgetDivs() instead of static

- doc/CHANGES.md
- doc/README.md
- src/gridstack.ts
* added option to force re-creation of the drag&drop event binding
> prepareDragDrop(el, force)

- src/gridstack.ts
- src/types.ts
#2667 
These changes fix sidebar items not honoring gs-w and gs-h when dragging between multiple grids. When dragging between multiple grids, the size of the widget is limited by nodeBoundFix() based on number of columns. Eg. if you enter a grid which limits the gs-w attribute then enter another grid, I would expect the gs-w to honor the original size defined in the sidebar item, but instead it keeps the value which was limited in the previous grid.
These changes add another property for tracking the sidebar item's original position, so any number of grids can be entered and it still respects the original size, only limiting gs-w when appropriate. The existing _gridstackNodeOrig logic was not sufficient to handle the different behavior of the sidebar item.
These changes also fix another …
> #2667 Fixed sidebar items not honouring gs-w

- angular/projects/lib/src/lib/gridstack-item.component.ts
- angular/projects/lib/src/lib/gridstack.component.ts
- doc/CHANGES.md
- spec/gridstack-spec.ts
- src/gridstack.ts
* new `updateOptions(o: GridStackOptions)` to update PARTIAL list of options after grid as been created
> new updateOptions()

- doc/CHANGES.md
- src/gridstack.ts
> gs-size-to-content to support numbers

- doc/CHANGES.md
- src/gridstack.ts
> Locked not working as expected

- doc/README.md
- spec/gridstack-spec.ts
- spec/utils-spec.ts
- src/dd-resizable.ts
- src/gridstack.scss
- src/gridstack.ts
- src/types.ts
- src/utils.ts
> - Removed dynamic stylesheet and migrated to CSS vars

- doc/CHANGES.md
- spec/e2e/html/2947_load_responsive_list_smaller.html
- src/gridstack.ts
* fix #2947
* make sure we detect loading into a smaller responsive screen by re-using engine relayout code.
> loading into smaller screen with responsive layout:'list'

- doc/CHANGES.md
- package.json
- src/gridstack.ts
* `updateOptions()` no longer modifies passed in struct
* only field we check are being handled too
> `updateOptions()` no longer modifies passed in struct

- doc/CHANGES.md
- src/gridstack.ts
`resizeToContent()` fix for nested grid with content above
> `resizeToContent()` fix for nested grid with content above

- doc/CHANGES.md
- src/gridstack.ts
`resizeToContentCheck()` wasn't blocking _ignoreLayoutsNodeChange
> `resizeToContentCheck()` wasn't blocking _ignoreLayoutsNodeChange

- demo/events.js
- demo/nested.html
- doc/CHANGES.md
- src/gridstack.ts
* fix #2671
* Use `el.gridstackNode.grid` to know which (sub) grid if you care.
> subgrid now propagate events to topmost grid

- doc/CHANGES.md
- src/dd-draggable.ts
- src/gridstack.scss
> remove no-op 'cursor: move' CSS

- doc/CHANGES.md
- src/gridstack.ts
* make sure nested items size they parent item even when in batch mode (eg: load()) otherwise it never happens
> nested grid resizeToContentCBCheck() fix

- doc/CHANGES.md
- src/gridstack.ts
> more `opts.animate`

- angular/projects/lib/src/lib/gridstack.component.ts
> more GridStack.updateCB

- src/gridstack-engine.ts
- src/gridstack.ts
See #3071 for description of issue. I added setting _loading to true in _prepareElement to fix the order issue and changed how we check if `node._id` is present (previously it would be false when called with the first element as it has an id of 0, not sure if this was wanted)
- [- ] Created tests which fail without the change (if possible)
- [X ] All tests passing (`yarn test`)
- [- ] Extended the README / documentation, if necessary
> fix: makeWidget breakpoint layout issue #3071

- src/gridstack-engine.ts
Fixed a mistake I made in this PR https://github.com/gridstack/gridstack.js/pull/3072
`(node._id ?? false)` still is falsy when  `node_id = 0` 
- [-] Created tests which fail without the change (if possible)
- [-] Extended the README / documentation, if necessary
Also @adumesny  should I create a new issue for the incorrect order mentioned in #3071?
> fix: incorrect node._id check

- doc/README.md
- src/gridstack.ts
- src/types.ts
If gridstack is used in a complex layout, the browser layout can be interrupted by a [reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a) when the `getComputedStyle` function is called to ask for parent `min-height`.
To mitigate this in the `_updateContainerHeight`, it could be possible to give a priority if both `minRow` option and the `min-height` CSS property of the parent div are set. In this way, applications that sets `minRow` programmatically would never trigger the reflow.
Since `0` is the default value, and `null`/`undefined` values can be tricky to manage due to falsy/truly check in JS, to I would say that checking a non-zero/non-null value would be the solution. Users that wants "0" to be a valid row count and still disable the CSS check, could be pass something …
> Avoid reflows via explicitly setting minRow

- src/dd-resizable.ts
revert fix #3082 as that is incorrect fix and breaks nested grids as I suspected.
> revert #3083

- src/utils.ts
* fix #3099
* no example were given, but the code looks resonnable, but broke scrolling entire page so I fixed to take the scroll vs page into accound
Note: auto scrolling needs a major revamp (too fast) as well.
> scroll take into account ScrollContainer position

- react/lib/grid-stack-render-provider.test.tsx
- react/lib/grid-stack-render-provider.tsx
- react/package.json
- react/src/demo/demo.tsx
- react/vite.config.ts
- react/yarn.lock
This PR fixes the issue where multiple GridStack instances would crash when using the React integration due to shared state in the static GridStack.renderCB callback (#2937).
Problem: The static GridStack.renderCB was being shared across all GridStack instances, causing widget container references to be mixed up between different grids. This led to crashes and incorrect behavior when multiple grids were present on the same page.
•  Added a gridWidgetContainersMap WeakMap that uses the GridStack instance as the key
•  Each grid instance now maintains its own isolated widget container map
•  The WeakMap ensures automatic memory cleanup when grid instances are destroyed
```ts
// Before: All grids shared the same widget containers
GridStack.renderCB = (el, widget) => { …
```
> feat(test): add vitest setup and widget container tests

- demo/two_vertical.html
- doc/CHANGES.md
- src/gridstack.ts
* fix #3021 
* correctly reset widget back (to last known position) when released outside (to last known position) when released outside
> correctly reset widget back

- angular/projects/lib/src/lib/base-widget.ts
- angular/projects/lib/src/lib/gridstack-item.component.ts
- angular/projects/lib/src/lib/gridstack.component.ts
- angular/projects/lib/src/lib/gridstack.module.ts
- angular/projects/lib/src/lib/types.ts
> improved angular code doc

- doc/API.md
- doc/CHANGES.md
- spec/utils-spec.ts
- src/utils.ts
* since we don't know how to hydrate arrays (unlike object spread operator '...') skip them)
> fix Util:removeInternalForSave() to skip arrays

- react/lib/grid-stack-provider.tsx
resolving the issue where only the internal elements were removed when an ID was provided. Passing the element now ensures that the entire grid-stack-item-content is removed as intended.
> Fix bug where removeWidget does not function properly

- doc/API.md
remove HTMLElement from GridStackElement type in API documentation
> remove HTMLElement from GridStackElement type in API documentation
