gridstack/gridstack.js

bower.json

add this package requirements to bower dependencies

Update bower.json to have dependencies

---

README.md
src/gridstack.js

To fix #184, since it seems that a node created by javascript, must also be modified by javascript afterward.

Add an API to set minWidth and minHeight to a node

---

src/gridstack.js

#116 
- added remove_stylesheet
- changed on_resize_hander to allow unbinding
- added destroy method

Add Destroy method

---

bower.json
package.json

I added a package.json so this can be published as an npm package. I already published it to npm but will transfer control whenever you want.
See any problems with the actual commit itself?

Setup as an npm package

---

README.md

improved readability

---

src/gridstack.js

the will fix #177.
also fix drag handle option being hard coded.
and i finally added some sort of limit to when the collision detection is fired when dragging a widget. now collision detection will only work when you move/drag the widget an amount equal to one unit.

performance and other fixes

---

src/gridstack.js

fixes #159 by making grid item callbacks actual event callbacks instead of options callbacks

fix ordering of draggable and resizable event callbacks

---

src/gridstack.js

Listeners are resizestart and resizestop, but option names are start and stop.

Fixed names of options.

---

README.md
doc/README.md
package.json

Functionality for #114 already existed - simply added info to API docs.

#114 Add setAnimate(doAnimate) to API docs.

---

demo/anijs.html
demo/float.html
demo/knockout.html
demo/knockout2.html
demo/nested.html
demo/responsive.html
demo/rtl.html
demo/serialization.html
demo/two.html

Users will be downloading and testing demo's on local machine which will result in CDN's failing

Add https to CDN's with only network-path references.

---

demo/responsive.html

Delete not needed </script> tag

Delete not needed </script> tag

---

src/gridstack.js

Reverts troolee/gridstack.js#532

Revert "fixed ie8 not support"

---

doc/README.md
src/gridstack.js

In my project, I need to disable the oneColumnMode, to be able to change the number on column manually when the user is on a small screen.
Maybe it can help someone else

An option to disable the oneColumn mode

---

README.md

readme CDN updated to 0.3.0
Bug Number:
Documentation Notes:
PrecheckinTest URL: foo.com
QA Notes:
Review URL: foo.com
Reviewed by: adumesny
Testing Done: trivial change - CDN files exist

Description: readme CDN updated to 0.3.0

---

bower.json
karma.conf.js
package-lock.json
package.json

Tests were failing - fixed this. Fixed some security vulnerabilities.
- [ x] Created tests which fail without the change (if possible)
- [ x] All tests passing (`npm test`)
- [ x] Extended the README / documentation, if necessary

More housekeeping / fix tests

---

.gitignore
.npmignore
bower.json
doc/CHANGES.md
package-lock.json
package.json
src/gridstack.js

…so that hopefully I don't ruin everyone's builds when I update npm.

Switch to 0.4.0-dev

---

.travis.yml
karma.conf.js
package-lock.json
package.json
spec/gridstack-spec.js

Update Travis, use Chrome Headless for tests

---

src/gridstack.js

I added event "gsresize" for each "grid-stack-item" fired immediately once widget is resized. I will use it to choose specific knockout template for content according item height.

added "gsresize" trigger

---

doc/CHANGES.md
package.json
src/gridstack.js

* update changelog to fix typos, added lodash removal, changed urls
* also removed mkdir /dist which gives error if already there. Build creates it anyway.

changelog.md update

---

bower.json
doc/CHANGES.md
package.json
src/gridstack.jQueryUI.js
src/gridstack.js

0.6.0-dev name change for upcoming dev work now that 0.5 is out.

0.6.0-dev name change

---

.gitignore
.npmignore
bower.json
doc/CHANGES.md
doc/README.md
package.json
src/gridstack.jQueryUI.js
src/gridstack.js

* reduced npm package from 672k to 324k (drop demo, src and extra files)
* fix API doc, tweaked package credits
rev 0.5.1

reduced npm package

---

Gruntfile.js
doc/CHANGES.md
src/gridstack.d.ts

* this file is small and make it much easier for TS users not to @types/gridstack
* makes it much easier for me update as code changes in 1 repo

added TS type definition file from DefinitelyTyped

---

doc/CHANGES.md
spec/gridstack-spec.js
src/gridstack.js

null values to addWidget() exception fix

---

src/gridstack.d.ts

* reformatted file (beautify) to 2 space
* removed @param types as those are induced by method (code hint works)
and tslint will complain with strict on.
tested against my TS app.

format tweak to typescript def file

---

.gitignore
index.html

* added a bulleted feature list (easier to see features)
* added more demos (with index list - better to list than have nothing)
* tune down add/remove buttons
* Why use section

web page updates

---

demo/anijs.html
demo/float.html
demo/knockout.html
demo/knockout2.html
demo/nested.html
demo/responsive.html
demo/right-to-left(rtl).html
demo/serialization.html
demo/two.html
index.html

so we don't have to update them each release, unless content needs to change

switch demos to gridstack@latest

---

demo/advance.html
demo/index.html
demo/two.html
doc/CHANGES.md

thanks @DigitalJo for suggestion  #1067

advance demo from web page

---

demo/two.html

demo tweak for #924
* updated two.html to have some min/max/id contrain to copy over
Note: all data-gs- props are there, but the resize/move feedback isn't totally in sync. Will file separate issue.

widget properties when dropping it into other grid

---

demo/advance.html
demo/anijs.html
demo/demo.css
demo/float.html
demo/index.html
demo/knockout.html
demo/knockout2.html
demo/nested.html
demo/responsive.html
demo/right-to-left(rtl).html
demo/serialization.html
demo/two.html
index.html

using 0.5.4 as apparently @latest isn't loading all.js correctly.

updated demos to latest lib and code

---

.gitignore
demo/advance.html
demo/anijs.html
demo/demo.css
demo/float.html
demo/knockout.html
demo/knockout2.html
demo/nested.html
demo/responsive.html
demo/right-to-left(rtl).html
demo/serialization.html
demo/two.html
index.html

updates to latest lib. test index and some samples.

0.5.5 release

---

demo/two.html

set grid-stack min-height so it doesn't collapse when empty

set grid-stack min-height

---

ISSUE_TEMPLATE.md
README.md

* updated bug template to latest rev, easier code

jsfiddle tweaks

---

src/gridstack.jQueryUI.js

* reverted some code that I didn't understand from #695
which was causing issues in my app. the `dragOut` makes sense to me, the other part not.

fix to .draggable from #1105

---

demo/two.html

acceptWidgets function example

---

bower.json
demo/column.html
doc/CHANGES.md
doc/README.md
package.json
spec/gridstack-spec.js
src/gridstack-poly.js
src/gridstack.d.ts
src/gridstack.jQueryUI.js
src/gridstack.js

don't know why it's trying to merge stuff already there,,,, agrr.

rev 0.6.2-dev

---

demo/demo.css
demo/index.html
index.html

* adding `gridstack-extra.min.css` for now until 0.6.3 comes out
this fix #1132

webpage fix for oneColumnMode

---

README.md
demo/two.html

added info on how to extend library

---

README.md

Updated README to use the correct name for the ember project

README Update : Update name on ember project

---

README.md

Updated link to the sample projects folder

Update: Readme link to sample projects

---

demo/two.html

* to show issue #997 (maxWidth not carring totally over on drop as shadow still resizes past that)

updated two.html to show maxWidth issue

---

doc/CHANGES.md
doc/README.md
src/gridstack.js

* code and doc tweaks for #1172

`minRow` tweaks

---

demo/column.html
demo/responsive.html

website fix missing extra.css

---

src/gridstack.ts
src/utils.ts

Work in progress. Replaced some `jQuery` with native while keeping the `jQuery` calls around for reference.

TS: Replace some `jQuery`

---

doc/CHANGES.md
doc/README.md
spec/gridstack-spec.js
src/gridstack.d.ts
src/gridstack.js

* regression bug fix for #1229

`staticGrid` no longer disable oneColumnMode

---

README.md
demo/advance.html
demo/anijs.html
demo/column.html
demo/experiment/test.html
demo/experiment/test2.html
demo/float.html
demo/knockout.html
demo/locked.html
demo/nested.html
demo/responsive.html
demo/right-to-left(rtl).html
demo/serialization.html
demo/two.html
doc/README.md
spec/e2e/gridstack-html-spec.js
spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
spec/e2e/html/1142_change_event_missing.html
spec/e2e/html/1143_nested_acceptWidget_types.html
spec/e2e/html/1155-max-row.html
spec/e2e/html/810-many-columns.html
spec/e2e/html/events.html
spec/gridstack-engine-spec.ts
spec/gridstack-spec.ts
spec/utils-spec.ts
src/gridstack-engine.ts
src/gridstack.ts
src/types.ts
src/utils.ts

* added a bunch of test cases to covert all methods (appart for events and drag&drop callbacks)
* found couple issues in code while writing those tests!
(what they are supposed to be for)
* replaced all `var` with `let`
part of #1084
next up: remove all jquery from main code

TS: big code coverage increase

---

demo/float.html
spec/gridstack-spec.ts
src/gridstack-dragdrop-plugin.ts
src/gridstack.ts
src/jqueryui-gridstack-dragdrop-plugin.ts
src/utils.ts

* only 10 $ instances left - mostly events drag&drop
* converted couple jquery events callbacks to plain vanilla... more todo
part of #1084

TS: more jquery removal

---

src/gridstack.js

Do not rely on options Object.prototype

---

doc/CHANGES.md

changelist for #1195

---

doc/CHANGES.md
webpack.config.js

TS develop -> typescript

---

package.json
spec/gridstack-engine-spec.ts
src/gridstack-engine.ts
src/gridstack.ts
webpack.config.js

introduced during the jquery-ui removal.

TS: fix when dragging to delete and back

---

doc/CHANGES.md
doc/README.md
src/gridstack-engine.ts
src/gridstack.ts

and use typescript default value

TS: detachNode -> removeDOM rename

---

src/gridstack.ts
src/types.ts
src/utils.ts
webpack.config.js

* GridStackNode.grid is not hidden (was _grid)
* doc updated to hide more private members

TS: doc/types cleanup

---

doc/README.md

Corrected makeWidget sample code and tested in codepen

Corrected makeWidget sample code

---

README.md
demo/serialization.html
doc/CHANGES.md
doc/README.md
spec/gridstack-spec.ts
src/gridstack-engine.ts
src/gridstack.ts
src/types.ts
src/utils.ts

* added new api to save and relod  layouts and test cases showing usage
* GridstackWidget -> GridStackWidget typo fix

#1286 new save()/restore() API

---

src/gridstack.ts

make sure height is rounded width when set to auto (don't need partial pixels)

TS: more fix for #810 many columns roundoff error

---

README.md
doc/CHANGES.md

TS: doc update

---

.eslintignore
Gruntfile.js
demo/float.html
demo/two.html
package.json
spec/gridstack-spec.ts
src/gridstack-dd.ts
src/gridstack.ts
src/index.ts
src/jq/gridstack-dd-jqueryui.ts
src/types.ts
webpack.config.js
yarn.lock

renamed
GridStackDragDropPlugin -> GridStackDD
JQueryUIGridStackDragDropPlugin -> GridStackDDJQueryUI
* gridstack.all.js is now generated (190k) optimized with map and works great
* gridstack.js is also generated and complete without JQ anything and works great
* jq + jqui are now generated as min with map and appears to be OK
only thing remaining is to get gridstack-dd-jqueryui.js generated as stand alone file that could be imported.
(webpack will bundle dependencies so I need separate rule OR get tsc to do that

TS: progress on bundling for build, renamed DD files

---

spec/e2e/html/1017-items-no-x-y-for-autoPosition.html
spec/e2e/html/1102-button-between-grids.html
spec/e2e/html/1142_change_event_missing.html
spec/e2e/html/1143_nested_acceptWidget_types.html
spec/e2e/html/1155-max-row.html
spec/e2e/html/1286-load.html
src/gridstack-engine.ts
src/gridstack.ts

* more fixed for #1286
* load() was not correctly clearing the HTML items, and calling removed callback
* added sample text case
* also fixed other use cases includes

TS: more fixed for load()

---

src/jquery.js

restore jquery to ship version. part of #1341.
tested locally and seems ok, so not sure why I had to comment out before...

more UMD support

---

README.md
demo/two.html
doc/CHANGES.md
package.json
src/gridstack-extra.scss
src/gridstack-poly.js
src/gridstack.d.ts
src/gridstack.jQueryUI.js
src/gridstack.js
src/gridstack.scss
src/jquery.js

rev 1.2.1 release

---

README.md
package.json
src/gridstack-dd.ts
src/gridstack-engine.ts
src/gridstack-extra.scss
src/gridstack-poly.js
src/gridstack.scss
src/gridstack.ts
src/jq/gridstack-dd-jqueryui.ts
src/types.ts
src/utils.ts

TS: rev 2.0.0

---

demo/advance.html
demo/anijs.html
demo/column.html
demo/demo.css
demo/events.js
demo/knockout.html
demo/locked.html
demo/nested.html
demo/responsive.html
demo/right-to-left(rtl).html
demo/serialization.html
demo/two.html
index.html

changed to latest demo versions and v2.0.0 release

rev 2.0.0 update

---

src/dragdrop/dd-draggable.ts
src/dragdrop/dd-droppable.ts
src/dragdrop/dd-resizable.ts
src/dragdrop/dd-utils.ts

cherry picked last 4 changes from https://github.com/rhlin/gridstack.js feat-h5dd-optimize
would have loved to give him credit but wasn't sure how to merge for him, and didn't hear back...

H5 changed form rhlin

---

karma.conf.js
src/gridstack.ts
src/jq/gridstack-dd-jqueryui.ts
src/jq/jquery-ui.js
src/jq/jquery.js
webpack.config.js

see each commit - back to no change

attempt at let user bring own jquery libs

---

doc/CHANGES.md
spec/gridstack-spec.ts
src/gridstack.ts

id with number works (api that uses `GridStackElement` handle more string formats)

fix getting DOM element by number id

---

doc/CHANGES.md
doc/README.md
spec/gridstack-spec.ts
src/gridstack.ts
src/types.ts
src/utils.ts

* can now specify multiple margin values like CSS for all sides

setting margin option support CSS '5px 10px 0 20px' format

---

demo/two-h5.html
src/dragdrop/dd-base-impl.ts
src/dragdrop/dd-draggable.ts
src/dragdrop/dd-droppable.ts
src/dragdrop/dd-element.ts
src/dragdrop/dd-manager.ts
src/dragdrop/dd-resizable-handle.ts
src/dragdrop/dd-resizable.ts
src/dragdrop/dd-utils.ts
src/dragdrop/gridstack-dd-native.ts
src/gridstack.ts
src/index-h5.ts
src/index-jq.ts
src/index-static.ts
src/utils.ts
webpack.config.js

pushing all H5 changes (with history re-written) to be on top on v2.2.0-dev latest

H5: rebased from 2.2.0 latest code

---

src/dragdrop/dd-draggable.ts
src/dragdrop/dd-droppable.ts

* dragging items (from second grid) to trash will now actaully remove them
* dragLeave and drop will now share a lot of the callbacks cleanups

h5: you can now drag to trash to delete item

---

README.md
demo/index.html
doc/CHANGES.md

added link to Vue examples

---

src/gridstack-dd.ts
src/gridstack.ts
src/utils.ts

* from Omega-CMS fork on this code
https://github.com/Omega-CMS/omega-gridstack.js

null checks

---

src/h5/dd-base-impl.ts
src/h5/dd-draggable.ts
src/h5/dd-droppable.ts
src/h5/dd-resizable-handle.ts
src/h5/dd-resizable.ts
src/h5/dd-utils.ts
src/h5/gridstack-dd-native.ts
src/jq/gridstack-dd-jqueryui.ts

* made sure private member/method are hidden
* dd plugins export GridStackDD and types
since you need access to GridStackDD.get()

h5: code cleanup before release

---

src/gridstack.ts

more for #1471
* make sure we load() from last to first so any collision match 12 -> 1

more load() 1 column fixes

---

doc/CHANGES.md
doc/README.md
spec/gridstack-spec.ts
src/gridstack.ts

more for fix #1235
* moved the old individual routines to be hidden as update() does everything now
* updated doc which I forgot on last check in
* removed some old 0.5/0.6 backward compatible checks

more update(el, opts) changes

---

demo/nested.html
src/gridstack.ts

continue #1498
* addGrid() is now static as it can replace inti() method actually
* fixed nested.html demo to use it instead of load()
and fixed button actions.
* noticed dragOut:false is no longer working (even in JQ case). Will post bug.

more addGrid() fixes

---

.gitignore
node_modules/gridstack/dist/gridstack-extra.css
node_modules/gridstack/dist/gridstack.css

including both css so we don't break (if we copy from develop branch which doesn't use min)

web: CSS file fix

---

README.md

fixed migrate 1.x info

---

demo/index.html
demo/web-comp.html
doc/CHANGES.md
src/gridstack-extra.scss
src/gridstack.scss
src/gridstack.ts

* fix #1438
* make sure we handle grid size 0 when initializing things,
or we don' create CSS and bad things happen.
Also avoid oneColumnMode when no size.
* added webcomponent example
(more for debugging than anything)

web component fixes

---

webpack.config.js

build size  fix

---

demo/advance.html
index.html

* you can now drag new items into advance demo
* removed error code calling $().draggable which isn't there nor needed

web index demo fixes

---

spec/gridstack-spec.ts

column-N class fix test

---

index.html

* for #1413
* use JQ version and include before jquery.ui.touch-punch
* that MAY fix mobile devices. I have hard time debugging local file so trying to push to live server and see...

web: mobile fix

---

src/gridstack-engine.ts
src/utils.ts

fix spec tests

---

README.md

readme on JQ app

---

demo/index.html
demo/web1.html
demo/web2.html
src/gridstack-dd.ts
src/gridstack-engine.ts

* ran into inf loop when dragging from outside
* website demo update: added the 2 demos from website page to make it easier to test
(renamed advance.html -> web2)

collide: dragging from outside fix

---

demo/vue3js.html

added vue comment

---

src/gridstack-engine.ts

swap() now handles objects taking same columns (but different height)
as a simple swap (no further collision)
which optimizes current flow.
more #1094

collsion: swap working on different height

---

src/gridstack-dd.ts

restore items back when draggin in

---

LICENSE
doc/CHANGES.md

doc & license tweaks

---

src/gridstack-dd.ts
src/gridstack-engine.ts

* partial fix for #1687
last change to willItFit() broke this case. Working but still some issues...

collision: more 2 grids with maxRow

---

doc/CHANGES.md
doc/README.md
src/gridstack.ts
src/h5/dd-droppable.ts

doc updates

---

demo/website.html
doc/CHANGES.md

added the website file as demo for testing/sample
for #1745

added website index.html demo

---

spec/e2e/html/141_1534_swap.html

added 2 more cases (3 and 4) where collision is not working right.
re-opening #1094
(from #1737 discussion)

collision: re-open 1094

---

demo/two.html
doc/CHANGES.md
src/gridstack-dd.ts
src/gridstack.ts

* fix #1760
spec/e2e/html/1570_drag_bottom_max_row.html

`removable:true` working again (broke in 4.x)

---

demo/web1.html
demo/web2.html
doc/CHANGES.md
package.json
src/gridstack-dd.ts
src/gridstack-ddi.ts
src/gridstack-engine.ts
src/gridstack-h5.ts
src/gridstack-jq.ts
src/gridstack-poly.js
src/gridstack-static.ts
src/gridstack.scss
src/gridstack.ts
src/h5/dd-base-impl.ts
src/h5/dd-draggable.ts
src/h5/dd-droppable.ts
src/h5/dd-element.ts
src/h5/dd-manager.ts
src/h5/dd-resizable-handle.ts
src/h5/dd-resizable.ts
src/h5/dd-utils.ts
src/h5/gridstack-dd-native.ts
src/jq/gridstack-dd-jqueryui.ts
src/types.ts
src/utils.ts

JQ droppable fix for website

---

demo/angular-ngFor.ts
demo/angular.ts
demo/index.html

* partial fix for #1590
* added 2 angular based demos (.ts file as example)
* unfortunately I can't seem to get notification of changes for *ngFor loop and tracking the diference is a lot of work...
checking this for now.

Angular demos

---

karma.conf.js

* exclude the dummy demo/*.ts files for compile

fixed karma test

---

demo/float.html

wasn't supposed to be pushed in.

float demo cleanup

---

doc/CHANGES.md
src/h5/dd-draggable.ts

restore animation when dragging items

---

doc/CHANGES.md
src/h5/dd-draggable.ts

fix for #1973
* added a timeout > 0 to reset animation back so values have a chance to render...

DnD Snap to Animation fix

---

demo/drag-and-drop-dataTransfer-angular.ts
demo/drag-and-drop-dataTransfer.html
demo/static.html
demo/two.html
demo/web2.html
demo/website.html
doc/README.md
spec/e2e/html/1143_nested_acceptWidget_types.html
spec/e2e/html/1419-maxrow1-cant-insert.html
spec/e2e/html/1571_drop_onto_full.html
spec/e2e/html/1704_scroll_bar.html
src/dd-draggable.ts
src/dd-gridstack.ts
src/gridstack.ts
src/types.ts

* removed revert: 'invalid', scroll: false support as those were never implemented in H5
* combined more classes and moved DD around

more jquery cleanup

---

README.md
demo/canvasJS.html
demo/website.html
doc/CHANGES.md
package.json
spec/e2e/html/1142_change_event_missing.html
src/dd-base-impl.ts
src/dd-draggable.ts
src/dd-droppable.ts
src/dd-element.ts
src/dd-gridstack.ts
src/dd-manager.ts
src/dd-resizable-handle.ts
src/dd-resizable.ts
src/dd-touch.ts
src/gridstack-engine.ts
src/gridstack-poly.js
src/gridstack.scss
src/gridstack.ts
src/types.ts
src/utils.ts

rev 6.0.0-dev

---

doc/README.md

Updated acceptWidget's documentation.

Updated acceptWidget's documentation

---

demo/website.html
index.html

* not sure as this one is good for 30 days only. prev one expired but was good for years...
for #2057

updated invite link

---

doc/CHANGES.md
src/gridstack-engine.ts
src/gridstack.ts

added GridStackEngine.findEmptyPosition()

added GridStackEngine.findEmptyPosition()

---

package.json

added MIT license back to package.json

---

demo/index.html
demo/offset.html

* this shows that fix #1820 with latest 7.x code adding a demo with parent offseted working as expected.

demo for parent offset

---

demo/angular/src/app/app.component.html
demo/angular/src/app/app.module.ts
demo/angular/src/app/ngFor.ts
demo/angular/src/app/ngFor_cmd.ts
demo/index.html

* fixed original AngularNgForCmdTestComponent to correctly delete objects. added to demo list

more angular updates

---

demo/angular/src/app/ngFor.ts
demo/angular/src/app/ngFor_cmd.ts
demo/index.html

* showing how new layouts can be created while preserving old items if needed.

more angular demo tweaks

---

demo/events.js
doc/CHANGES.md
src/gridstack.ts
src/types.ts

* GridStackEventHandlerCallback is not a list of specific callbacks so user can have better method signatures.

better GridStackEventHandlerCallback types

---

demo/vue2js.html
demo/vue3js.html

* fix #1832
* removed comments about 'this' in vue3 demo and make the function local

Vue demo cleanup

---

src/dd-draggable.ts

* fix while debugging #1936
* no longer leave min-width & will-change after a drag

remove dragged style after done

---

demo/index.html
demo/react-hooks-controlled-multiple.html

Demo - multiple react grids example

---

demo/index.html
demo/react-hooks-controlled-multiple.html
demo/react-hooks.html

React 2 grid demo
* fix #2094
* now works dragging between grids and staying in sync. Still not recommended way...
*

partially fixed Rect complex example

---

demo/react-hooks-controlled-multiple.html

web demo fix

---

demo/angular/src/app/README.md
demo/angular/src/app/app.component.html
demo/angular/src/app/app.component.ts
demo/angular/src/app/gridstack-item.component.ts
demo/angular/src/app/gridstack.component.ts
demo/angular/src/index.html
doc/CHANGES.md
package.json
src/gridstack.ts
yarn.lock

for some reason it's ringing old changes along...
Angular wrapper fix - HTML template
* fix `addWidget()` to handle passing just {el} which was needed for Angular HTML template demo
* added HTML template to angular demo and fix wrapper accordingly

Angular wrapper fix - HTML template

---

demo/angular/src/app/app.component.ts
demo/angular/src/app/app.module.ts
demo/angular/src/app/dummy.component.ts
demo/angular/src/app/gridstack-item.component.ts
demo/angular/src/app/gridstack.component.ts

* show creating grid items content components on the fly by type (rather than hard code in template)

Angular demo update

---

Gruntfile.js
src/gridstack.scss

css tweaks

---

demo/esmodule.html
demo/index.html

but it gives CORS errors trying to load locally...

added esmodule.html test

---

doc/README.md

Doc update for disableOneColumnMode.

chore: wrote disableOneColumnMode's doc clearly

---

demo/angular/package.json
demo/angular/yarn.lock

latest rev of all the packages - @angular/core@15.2.8 and ts < 5.0

Angular yarn upgrade --latest

---

doc/CHANGES.md
src/gridstack.scss

ne nw resize handle

---

spec/e2e/html/810-many-columns.css
src/gridstack-extra.scss
src/gridstack.scss

back to 1000 precision (60 columns showed artifact with 100)

more css tweaks

---

src/gridstack-engine.ts
src/gridstack.ts

* fix #404
* make sure to use batch mode to improve re-layout

auto-size content batch mode

---

src/gridstack.ts

* based on review #2412 for bug #404
* now have clone list, and using firstElementChild checking for NULL for correct sizing

more fitToContent fixes

---

angular/projects/lib/package.json
angular/projects/lib/src/lib/base-widget.ts
angular/projects/lib/src/lib/gridstack-item.component.ts
angular/projects/lib/src/lib/gridstack.component.ts
angular/projects/lib/src/lib/gridstack.module.ts
doc/CHANGES.md
package.json
src/dd-base-impl.ts
src/dd-draggable.ts
src/dd-droppable.ts
src/dd-element.ts
src/dd-gridstack.ts
src/dd-manager.ts
src/dd-resizable-handle.ts
src/dd-resizable.ts
src/dd-touch.ts
src/gridstack-engine.ts
src/gridstack-poly.js
src/gridstack.scss
src/gridstack.ts
src/types.ts
src/utils.ts

* callbacks where not called due to casing issue

9.0.1-dev && 'resizecontent' event fix

---

demo/vue3js.html

Fix type mistake

---

demo/responsive.html

update responsive demo to latest options

---

doc/CHANGES.md
src/gridstack.scss

* fix #2496
* fix animation on init, introduced in 8.1.1

animation on init fix

---

ISSUE_TEMPLATE.md
demo/website.html

more slack link

---

demo/column.html
demo/custom-engine.html

fix column demo links

---

README.md

doc fix on columnOpts

---

doc/CHANGES.md
src/gridstack.ts

fix #2577 missing resize styles

fix #2577 missing resize styles

---

demo/nested.html
src/gridstack.ts

better fix for #2590 - more todo..

demo: nested drop

---

src/dd-draggable.ts
src/dd-droppable.ts
src/dd-element.ts
src/dd-resizable-handle.ts
src/dd-resizable.ts
src/gridstack.ts

* no reason to have constructor params and class vars assigned to them.

construction vars code cleanup

---

angular/projects/demo/src/app/app.component.ts

added ng component input example

added ng component input example

---

src/utils.ts

removeInternalAndSame() tweak

---

README.md
index.html
package.json
src/styles/highlight.css

- Updated the favicon by removing "shortcut" from the rel attribute to ensure better compatibility.
- Removed jQuery and replaced the old jQuery scripts with vanilla JavaScript to improve performance.
> I'm unsure about the quality of this new script if you can check briefly it could be nice.
- Replaced the old Ionic icons with SVGs from the Lucide icon library to modernize and unify the visuals.
- Enhanced the design by adding colors to different sections.
Introduced a custom theme to highlight.js to enhance syntax visibility.
- Updated the documentation by adding highlights.js explanations & roadmap updates

Favicon+clean-code+icons

---

src/dd-draggable.ts
src/utils.ts

build fix. added Utils.swap()

---

angular/angular.json
doc/CHANGES.md
package.json

set packageManager for mac build

---

doc/CHANGES.md
src/gridstack.ts

more load() now creates in order fixes

---

index.html
package.json
src/scripts/fetch-latest-github-release.js
src/scripts/fetch-release.js

Add a dynamic `<span>` to get the latest release version name on the home page
> A format have also been applied with `yarn run format-fix`

Automate latest release on home page

---

angular/angular.json
angular/projects/demo/src/styles.css

fix angular demo styles

---

angular/README.md

fix angular doc

---

angular/README.md

angular doc update: custom input

---

angular/projects/demo/src/app/dummy.component.ts
angular/projects/lib/src/lib/base-widget.ts
angular/projects/lib/src/lib/gridstack-item.component.ts
angular/projects/lib/src/lib/gridstack.component.ts
angular/projects/lib/src/lib/gridstack.module.ts
src/dd-base-impl.ts
src/dd-draggable.ts
src/dd-droppable.ts
src/dd-element.ts
src/dd-gridstack.ts
src/dd-manager.ts
src/dd-resizable-handle.ts
src/dd-resizable.ts
src/dd-touch.ts
src/gridstack-engine.ts
src/gridstack-extra.scss
src/gridstack-poly.js
src/gridstack.scss
src/gridstack.ts
src/types.ts
src/utils.ts

null check, date change

---

angular/projects/demo/src/app/app.component.html
angular/projects/demo/src/app/app.component.ts
angular/projects/demo/src/app/dummy.component.ts
angular/projects/lib/src/lib/gridstack-item.component.ts
angular/projects/lib/src/lib/gridstack.component.ts
demo/lazy_load.html
doc/CHANGES.md
doc/README.md
src/types.ts
src/utils.ts

angular support for lazyLoad + demo

---

spec/gridstack-engine-spec.ts
spec/test.html
src/dd-resizable-handle.ts
src/gridstack.ts

fixed engine test to run again
TODO: main test

fixed engine test to run again 

---

angular/projects/demo/src/app/app.component.html
doc/CHANGES.md
react/lib/constants.ts
spec/gridstack-engine-spec.ts
spec/gridstack-spec.ts
spec/test.html
src/gridstack-engine.ts
src/gridstack.ts

fix main test and bug

---

doc/CHANGES.md
spec/gridstack-engine-spec.ts
spec/gridstack-spec.ts
spec/test.html
src/gridstack-engine.ts
src/gridstack.ts

* for #2851 make sure to update the value and added some better testing (grid, not engine that behaves differently).

large layout saving tweaks

---

doc/CHANGES.md
src/gridstack.ts
src/types.ts

* fix #2886
* untested but should be fine :)

added `gs-size-to-content` support

---

doc/README.md

attr `data-gs-widget` doc

---

demo/index.html
demo/vue3js_dynamic-modern-renderCB.html

Updated demo index page to include vue3 renderCB demo

updated demo index page to include vue3 renderCB demo

---

spec/gridstack-spec.ts
src/gridstack.ts

* fix in test for #2852
* also fixed tests for this._placeholder being null

yarn test STYLE fixes

---

spec/e2e/html/2729_web_component_drag_esc.html

* added a test case for #2729 (thought it was about Esc, but it's about draggable.cancel option not working.

web component .no-drag test

---

src/dd-gridstack.ts

optimize DDGridStack to not create on destroy/disable

optimize DDGridStack to not create on destroy/disable

---

spec/gridstack-spec.ts
src/gridstack.ts

* fixed #2964 yarn test breaking (good thing for unit tests!)

minW yarn test fixes

---

src/dd-touch.ts

dd-touch import fix

---

demo/web2.html
doc/CHANGES.md
src/gridstack.ts
src/types.ts

revert this change lock change
SHA-1: 5321400b73f23b746581bb0b5e57f89fcfefa684
* Locked not working as expected
* fix #2981

revert this change lock change

---

spec/gridstack-spec.ts
spec/regression-spec.ts
src/gridstack.ts

removed obsolete _styleSheetClass + fixed test cases

---

src/gridstack.ts

* incorrect logic during updateOptions() making minRow=undefined, which messed getRow.

fix opts.minRow being undefined

---

doc/CHANGES.md
src/gridstack.ts

fix `opts.animate` again

---

README.md
doc/CHANGES.md

doc update

---

doc/CHANGES.md
src/gridstack.ts

* shoudl fix #3085 (though no posted example)

call _updateContainerHeight() when changing opts.minRow

---

doc/CHANGES.md
doc/README.md
src/types.ts

doc fix for #3054

---

doc/API.md
doc/CHANGES.md
src/dd-resizable-handle.ts
src/dd-resizable.ts
src/types.ts

tweak to DDResizeOpt

---

angular/projects/lib/src/lib/base-widget.ts
angular/projects/lib/src/lib/gridstack-item.component.ts
angular/projects/lib/src/lib/gridstack.component.ts
angular/projects/lib/src/lib/gridstack.module.ts
angular/projects/lib/src/lib/types.ts
package.json
src/gridstack.ts
src/utils.ts
tsconfig.build.json

yarn lint fixes

---

react/lib/grid-stack-context.ts
react/lib/grid-stack-provider.tsx

Add removeAll function to react wrapper
